"""
Additional Botanical Database for Andhra Pradesh Regional Trees, Crops, Vegetables, Flowers, and Weeds.
Merged into the central PLANT_DATABASE.
"""

ANDHRA_SPECIES_DATABASE = {
    # ==================== BIG NATIVE & TIMBER TREES ====================
    "red_sanders": {
        "common_name": "Red Sanders / Red Sandalwood",
        "regional_names": {
            "te": "ఎర్రచందనం (Erra Chandanam)",
            "hi": "लाल चंदन (Lal Chandan)",
            "ta": "செஞ்சந்தனம் (Senchandanam)",
            "kn": "ರಕ್ತ ಚಂದನ (Rakta Chandana)",
            "ml": "രക്തചന്ദനം (Raktachandanam)",
            "mr": "रक्तचंदन (Raktachandan)"
        },
        "scientific_name": "Pterocarpus santalinus",
        "family": "Fabaceae (Legume Family)",
        "category": "Normal Tree (పెద్ద చెట్లు / వృక్ష జాతి)",
        "description": "Endemic precious hardwood tree of Seshachalam and Palakonda hills of Rayalaseema, prized globally for deep crimson heartwood.",
        "native_region": "Seshachalam Hills, Andhra Pradesh",
        "growth_stage": "Perennial Slow-growing Timber Tree",
        "growing_season": "Monsoon planting",
        "harvest_season": "25 - 30 years for heartwood maturation",
        "soil_type": "Dry gravelly rocky hillsides (pH 6.5 - 7.5)",
        "temperature_range": "20°C - 44°C",
        "water_requirement": "Low (High drought resilience)",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Organic compost in monsoon",
        "economic_importance": "Extremely high value luxury timber export and traditional Ayurveda.",
        "common_uses": ["Carvings & Musical Instruments", "Ayurvedic Skin Medicine", "Precious Wood Export"],
        "common_diseases": ["Heart Rot", "Leaf Spot"],
        "common_pests": ["Stem Borer", "Leaf Webbers"]
    },
    "rosewood": {
        "common_name": "Indian Rosewood / Shisham",
        "regional_names": {
            "te": "ఇరుగుడు / రోజ్వుడ్ (Irugudu Chettu)",
            "hi": "शीशम (Shisham)",
            "ta": "ஈட்டி மரம் (Eeti Maram)",
            "kn": "ಬೀಟೆ ಮರ (Beete Mara)",
            "ml": "ഈട്ടി (Eetti)",
            "mr": "शिसव (Shisav)"
        },
        "scientific_name": "Dalbergia latifolia",
        "family": "Fabaceae (Legume Family)",
        "category": "Normal Tree (పెద్ద చెట్లు / వృక్ష జాతి)",
        "description": "Deciduous forest timber tree known for its rich dark purple-brown heartwood, strength, and premium furniture polish.",
        "native_region": "Southern & Central India",
        "growth_stage": "Perennial Hardwood Tree",
        "growing_season": "Monsoon flush",
        "harvest_season": "20 - 40 years for commercial timber",
        "soil_type": "Deep well-drained moist alluvial and red loamy soils",
        "temperature_range": "18°C - 40°C",
        "water_requirement": "Moderate",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Self nitrogen-fixing leguminous tree",
        "economic_importance": "Top-tier cabinet, carving, and furniture export timber.",
        "common_uses": ["High-end Furniture", "Decorative Veneers", "Musical Instrument Fretboards"],
        "common_diseases": ["Fusarium Wilt", "Powdery Mildew"],
        "common_pests": ["Defoliator Caterpillars", "Timber Wood Borers"]
    },
    "babool": {
        "common_name": "Babool / Gum Arabic Tree",
        "regional_names": {
            "te": "తుమ్మ చెట్టు / నల్ల తుమ్మ (Thumma Chettu)",
            "hi": "बबूल (Babool)",
            "ta": "கருவேலம் (Karuvelam)",
            "kn": "ಜಾಲಿ ಮರ (Jaali Mara)",
            "ml": "കരിവേലം (Karivelam)",
            "mr": "बाभळ (Babhul)"
        },
        "scientific_name": "Vachellia nilotica",
        "family": "Fabaceae (Legume Family)",
        "category": "Normal Tree (పెద్ద చెట్లు / వృక్ష జాతి)",
        "description": "Hardy thorny tree of arid Rayalaseema and coastal plains, yielding natural gum arabic, hard timber, and nutritious goat fodder.",
        "native_region": "Indian Subcontinent & Africa",
        "growth_stage": "Spiny Perennial Canopy Tree",
        "growing_season": "Year-round",
        "harvest_season": "Perennial resin and pod collection",
        "soil_type": "Black cotton soils, dry gravel, and saline lands",
        "temperature_range": "15°C - 45°C",
        "water_requirement": "Very Low",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "None (Nitrogen fixing)",
        "economic_importance": "Gum Arabic production and agricultural plough construction.",
        "common_uses": ["Gum Arabic", "Agricultural Implements", "Dental Twigs (Datun)"],
        "common_diseases": ["Damping Off", "Stem Canker"],
        "common_pests": ["Bagworms", "Bruchid Seed Beetles"]
    },
    "subabul": {
        "common_name": "Subabul / River Tamarind",
        "regional_names": {
            "te": "సుబాబుల్ (Subabul)",
            "hi": "सुबबूल (Subabool)",
            "ta": "சவுண்டல் (Soundal)",
            "kn": "ಸುಬಾಬುಲ್ (Subabul)",
            "ml": "സുബാബുൽ (Subabul)",
            "mr": "सुबाभूळ (Subabhul)"
        },
        "scientific_name": "Leucaena leucocephala",
        "family": "Fabaceae (Legume Family)",
        "category": "Normal Tree (పెద్ద చెట్లు / వృక్ష జాతి)",
        "description": "Fast-growing nitrogen-fixing miracle tree widely cultivated across Andhra Pradesh for paper mill pulpwood and cattle fodder.",
        "native_region": "Central America (Naturalized across AP)",
        "growth_stage": "Fast-rotation Timber & Fodder (3-4 years)",
        "growing_season": "All seasons",
        "harvest_season": "3 - 4 years rotation",
        "soil_type": "Neutral to alkaline soils (Avoid high acidity)",
        "temperature_range": "20°C - 40°C",
        "water_requirement": "Low to Moderate",
        "sunlight_requirement": "Full Sunlight",
        "fertilizer_recommendation": "Phosphorus starter for root nodulation",
        "economic_importance": "Paper pulp supplier for ITC Bhadrachalam and AP Paper Mills.",
        "common_uses": ["Paper Pulpwood", "High-protein Livestock Fodder", "Biomass Fuelwood"],
        "common_diseases": ["Camptomeris Leaf Spot", "Root Rot"],
        "common_pests": ["Psyllid Bugs (Heteropsylla cubana)"]
    },
    "eucalyptus": {
        "common_name": "Eucalyptus / Nilgiri",
        "regional_names": {
            "te": "నీలగిరి / యూకలిప్టస్ (Neelagiri)",
            "hi": "नीलगिरी (Neelgiri)",
            "ta": "நீலகிரி (Neelagiri)",
            "kn": "ನೀಲಗಿರಿ (Neelagiri)",
            "ml": "യൂക്കാലിപ്റ്റസ് (Eucalyptus)",
            "mr": "नीलगिरी (Nilgiri)"
        },
        "scientific_name": "Eucalyptus tereticornis",
        "family": "Myrtaceae (Myrtle Family)",
        "category": "Normal Tree (పెద్ద చెట్లు / వృక్ష జాతి)",
        "description": "Rapidly growing straight tall agroforestry tree cultivated for poles, plywood, and paper pulp.",
        "native_region": "Australia (Widely cultivated in AP)",
        "growth_stage": "Fast-rotation Timber Tree (4-6 years)",
        "growing_season": "Monsoon planting",
        "harvest_season": "4 - 6 years coppice rotation",
        "soil_type": "Deep well-drained loam to red gravelly soils",
        "temperature_range": "15°C - 42°C",
        "water_requirement": "High in early establishment; drought hardy later",
        "sunlight_requirement": "Full Sunlight",
        "fertilizer_recommendation": "NPK 15-15-15 in planting pits",
        "economic_importance": "Major farmer revenue earner in social and farm forestry.",
        "common_uses": ["Paper Pulp & Plyboard", "Construction Scaffolding Poles", "Eucalyptus Leaf Oil"],
        "common_diseases": ["Cylindrocladium Leaf Blight", "Pink Disease"],
        "common_pests": ["Gall Wasp (Leptocybe invasa)", "Termites"]
    },
    "casuarina": {
        "common_name": "Casuarina / Beefwood",
        "regional_names": {
            "te": "సర్వి చెట్టు (Sarvi Chettu)",
            "hi": "झाऊ (Jhau)",
            "ta": "சவுக்கு (Savukku)",
            "kn": "ಗಾಳಿ ಮರ (Gaali Mara)",
            "ml": "കാറ്റാടി (Kattadi)",
            "mr": "सुरू (Suru)"
        },
        "scientific_name": "Casuarina equisetifolia",
        "family": "Casuarinaceae (Beefwood Family)",
        "category": "Normal Tree (పెద్ద చెట్లు / వృక్ష జాతి)",
        "description": "Premier coastal shelterbelt tree with needle-like photosynthetic twigs, fixing atmospheric nitrogen in sandy beach soils.",
        "native_region": "Indo-Pacific Coastlines",
        "growth_stage": "Rapid Tall Conifer-like Tree (3-5 years)",
        "growing_season": "Year-round coastal planting",
        "harvest_season": "3 - 5 years for scaffolding poles",
        "soil_type": "Beach sand, coastal sandy loam, and saline soils",
        "temperature_range": "20°C - 42°C",
        "water_requirement": "Low to Moderate once established",
        "sunlight_requirement": "Full Sunlight",
        "fertilizer_recommendation": "Symbiotic Frankia nitrogen fixation",
        "economic_importance": "Coastal cyclone windbreak, scaffolding poles, and high-heat firewood.",
        "common_uses": ["Cyclone Shelterbelt", "Scaffolding Timber", "High-caloric Fuelwood"],
        "common_diseases": ["Trichosporium Stem Canker", "Root Rot"],
        "common_pests": ["Bark-eating Caterpillars"]
    },
    "pongamia": {
        "common_name": "Pongamia / Indian Beech",
        "regional_names": {
            "te": "కానుగ చెట్టు (Kanuga Chettu)",
            "hi": "करंज (Karanj)",
            "ta": "புங்க மரம் (Punga Maram)",
            "kn": "ಹೊಂಗೆ ಮರ (Honge Mara)",
            "ml": "പുങ്ക് (Pungu)",
            "mr": "करंज (Karanj)"
        },
        "scientific_name": "Pongamia pinnata",
        "family": "Fabaceae (Legume Family)",
        "category": "Normal Tree (పెద్ద చెట్లు / వృక్ష జాతి)",
        "description": "Stout evergreen tree line widely planted on canal bunds and highways for bio-diesel seeds and green manure.",
        "native_region": "Indian Subcontinent",
        "growth_stage": "Perennial Spreading Canopy Tree",
        "growing_season": "Monsoon",
        "harvest_season": "Annual seed harvest in winter",
        "soil_type": "Alluvial, coastal, black and stony soils",
        "temperature_range": "18°C - 44°C",
        "water_requirement": "Low to Moderate",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Nitrogen-fixing leguminous tree",
        "economic_importance": "Biofuel seed oil and organic green manure foliage for paddy.",
        "common_uses": ["Bio-diesel Seed Oil", "Paddy Field Green Leaf Manure", "Avenue Shade"],
        "common_diseases": ["Anthracnose", "Rust"],
        "common_pests": ["Leaf Miner", "Galls"]
    },
    "flame_of_forest": {
        "common_name": "Flame of the Forest / Bastard Teak",
        "regional_names": {
            "te": "మోదుగ చెట్టు (Moduga Chettu)",
            "hi": "पलाश (Palash)",
            "ta": "பலாசு (Palasu)",
            "kn": "ಮುತ್ತುಗ (Muttuga)",
            "ml": "പ്ലാശ് (Plash)",
            "mr": "पळस (Palas)"
        },
        "scientific_name": "Butea monosperma",
        "family": "Fabaceae (Legume Family)",
        "category": "Normal Tree (పెద్ద చెట్లు / వృక్ష జాతి)",
        "description": "Medium deciduous tree erupting into brilliant orange-scarlet flowers in spring, sacred in Telangana and Andhra rural culture.",
        "native_region": "Indian Subcontinent",
        "growth_stage": "Deciduous Perennial Tree",
        "growing_season": "Spring floral canopy",
        "harvest_season": "Leaves harvested for dining plates",
        "soil_type": "Tolerates poor, saline, and waterlogged black soils",
        "temperature_range": "15°C - 44°C",
        "water_requirement": "Low",
        "sunlight_requirement": "Full Sunlight",
        "fertilizer_recommendation": "Self-sustaining nitrogen-fixer",
        "economic_importance": "Eco-friendly dining patra leaves, natural dyes, and sacred rituals.",
        "common_uses": ["Biodegradable Moduga Leaf Plates", "Natural Holi Herbal Dye", "Sacred Homa Fuel"],
        "common_diseases": ["Foliar Spot"],
        "common_pests": ["Lac Insects", "Leaf Webbers"]
    },
    "gulmohar": {
        "common_name": "Gulmohar / Royal Poinciana",
        "regional_names": {
            "te": "తురాయి / గుల్మొహర్ (Thurayi / Gulmohar)",
            "hi": "गुलमोहर (Gulmohar)",
            "ta": "மயிர்க்கொன்றை (Mayirkonrai)",
            "kn": "ಕೆಂపు ಕಲ್ತೊರೆ (Kempu Kaltore)",
            "ml": "ഗുൽമോഹർ (Gulmohar)",
            "mr": "गुलमोहर (Gulmohar)"
        },
        "scientific_name": "Delonix regia",
        "family": "Fabaceae (Legume Family)",
        "category": "Normal Tree (పెద్ద చెట్లు / వృక్ష జాతి)",
        "description": "Fast-growing umbrella-shaped flowering canopy tree famous for dramatic scarlet-orange blossoms across Andhra cities.",
        "native_region": "Madagascar (Universal in AP avenues)",
        "growth_stage": "Broad Canopy Shade Tree",
        "growing_season": "April - June peak flowering",
        "harvest_season": "Avenue shade throughout year",
        "soil_type": "Well-drained light loams and sandy soils",
        "temperature_range": "20°C - 42°C",
        "water_requirement": "Low to Moderate",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Organic compost in rainy season",
        "economic_importance": "Iconic landscape architecture and avenue shading.",
        "common_uses": ["Urban Avenue Shade", "Landscape Beautification", "Bee Forage"],
        "common_diseases": ["Root Rot in waterlogged soils"],
        "common_pests": ["Wood Boring Caterpillars"]
    },
    "copperpod": {
        "common_name": "Copperpod / Yellow Gulmohar",
        "regional_names": {
            "te": "కొండ చింత / పసుపు తురాయి (Konda Chinta)",
            "hi": "पीला गुलमोहर (Peela Gulmohar)",
            "ta": "பெருங்கொன்றை (Perungonrai)",
            "kn": "ಹಳದಿ ಗುಲ್ಮೊಹರ್ (Haladi Gulmohar)",
            "ml": "ചരക്കൊന്ന (Charakkonna)",
            "mr": "सोनमोहर (Sonmohar)"
        },
        "scientific_name": "Peltophorum pterocarpum",
        "family": "Fabaceae (Legume Family)",
        "category": "Normal Tree (పెద్ద చెట్లు / వృక్ష జాతి)",
        "description": "Massive canopy shade tree covered in golden yellow floral sprays and copper-colored pods along Andhra highways.",
        "native_region": "Tropical Asia",
        "growth_stage": "Large Perennial Shade Tree",
        "growing_season": "Summer golden flowering",
        "harvest_season": "Continuous avenue shade",
        "soil_type": "Sandy, coastal and gravelly soils",
        "temperature_range": "18°C - 42°C",
        "water_requirement": "Low to Moderate",
        "sunlight_requirement": "Full Sunlight",
        "fertilizer_recommendation": "None",
        "economic_importance": "Highway green belts and soil rehabilitation.",
        "common_uses": ["Highway Shade & Windbreak", "Landscape Parks", "Nitrogen enrichment"],
        "common_diseases": ["Collar Rot"],
        "common_pests": ["Scale Insects"]
    },
    "alstonia": {
        "common_name": "Devil's Tree / Scholar Tree",
        "regional_names": {
            "te": "ఏడాకుల పాల (Edakula Pala)",
            "hi": "सप्तपर्णी (Saptaparni)",
            "ta": "ஏழிலைப்பாலை (Ezilaipaalai)",
            "kn": "ಮದ್ದಾಲೆ (Maddale)",
            "ml": "ഏഴിലംപാല (Ezhilampaala)",
            "mr": "सातवीण (Saatveen)"
        },
        "scientific_name": "Alstonia scholaris",
        "family": "Apocynaceae (Dogbane Family)",
        "category": "Normal Tree (పెద్ద చెట్లు / వృక్ష జాతి)",
        "description": "Stately tiered evergreen tree with whorls of 7 leaves and intensely fragrant nocturnal winter flowers.",
        "native_region": "Indian Subcontinent",
        "growth_stage": "Tall Pagoda-tiered Evergreen Tree",
        "growing_season": "October - December flowering",
        "harvest_season": "Medicinal bark harvesting",
        "soil_type": "Moist loamy and alluvial soils",
        "temperature_range": "18°C - 38°C",
        "water_requirement": "Moderate",
        "sunlight_requirement": "Full Sun to Light Shade",
        "fertilizer_recommendation": "Organic compost in monsoon",
        "economic_importance": "Traditional Dita-bark febrifuge and light timber.",
        "common_uses": ["Anti-malarial Ayurvedic Bark", "Institutional Evergreen Landscaping", "Pencil Slates"],
        "common_diseases": ["Leaf Galls", "Blight"],
        "common_pests": ["Pauropsylla buxtoni (Gall maker)"]
    },
    "rain_tree": {
        "common_name": "Rain Tree / Saman",
        "regional_names": {
            "te": "నిద్రగన్నేరు చెట్టు (Nidraganneru Chettu)",
            "hi": "विलायती सिरीस (Vilayati Siris)",
            "ta": "தூங்குமூஞ்சி மரம் (Thoongumoonji Maram)",
            "kn": "ಮಳೆ ಮರ (Male Mara)",
            "ml": "മഴമരം (Mazhamaram)",
            "mr": "गुलाबी शिरीष (Gulabi Shirish)"
        },
        "scientific_name": "Samanea saman",
        "family": "Fabaceae (Legume Family)",
        "category": "Normal Tree (పెద్ద చెట్లు / వృక్ష జాతి)",
        "description": "Gigantic dome canopy shade tree lining Andhra irrigation canals and highways, famous for sleeping leaves at dusk.",
        "native_region": "Tropical America (Ubiquitous in AP)",
        "growth_stage": "Massive Wide-Spreading Canopy",
        "growing_season": "March - May pink powderpuff blooms",
        "harvest_season": "Continuous shade and sweet pod drop",
        "soil_type": "Deep moist alluvial soils",
        "temperature_range": "18°C - 40°C",
        "water_requirement": "Moderate",
        "sunlight_requirement": "Full Sunlight",
        "fertilizer_recommendation": "Nitrogen-fixing tree",
        "economic_importance": "Highway shade, cattle feed pods, and woodworking timber.",
        "common_uses": ["Canal & Roadside Giant Shade", "Nutritious Sweet Cattle Pods", "Carving Wood"],
        "common_diseases": ["Pink Limb Disease"],
        "common_pests": ["Mealybugs", "Boring Beetles"]
    },
    "sandalwood": {
        "common_name": "Indian Sandalwood",
        "regional_names": {
            "te": "చందనం చెట్టు / గంధం చెట్టు (Chandanam Chettu)",
            "hi": "चंदन (Chandan)",
            "ta": "சந்தன மரம் (Chandana Maram)",
            "kn": "ಶ್ರೀಗಂಧ (Srigandha)",
            "ml": "ചന്ദനം (Chandanam)",
            "mr": "चंदन (Chandan)"
        },
        "scientific_name": "Santalum album",
        "family": "Santalaceae (Sandalwood Family)",
        "category": "Normal Tree (పెద్ద చెట్లు / వృక్ష జాతి)",
        "description": "World-famous aromatic hemiparasitic tree whose fragrant heartwood and oil command unmatched global demand.",
        "native_region": "Southern India (Grown in AP farm plantations)",
        "growth_stage": "Hemiparasite Tree (Requires host roots)",
        "growing_season": "Perennial",
        "harvest_season": "15 - 25 years for heartwood extraction",
        "soil_type": "Well-drained red gravelly and loamy soils (Avoid standing water)",
        "temperature_range": "15°C - 38°C",
        "water_requirement": "Low to Moderate",
        "sunlight_requirement": "Full Sunlight",
        "fertilizer_recommendation": "Organic manure applied to host plants (Pongamia/Casuarina)",
        "economic_importance": "Extremely high value legal commercial plantation crop in Andhra Pradesh.",
        "common_uses": ["Sandalwood Oil Export", "Religious Deity Paste", "Luxury Carvings"],
        "common_diseases": ["Sandal Spike Phytoplasma"],
        "common_pests": ["Termites", "Stem Borers"]
    },
    "palmyra_palm": {
        "common_name": "Palmyra Palm / Asian Palmyra",
        "regional_names": {
            "te": "తాటి చెట్టు (Thati Chettu - AP State Tree)",
            "hi": "ताड़ (Taad)",
            "ta": "பனை மரம் (Panai Maram)",
            "kn": "ತಾಳೆ ಮರ (Taale Mara)",
            "ml": "പന (Pana)",
            "mr": "ताड (Taad)"
        },
        "scientific_name": "Borassus flabellifer",
        "family": "Arecaceae (Palm Family)",
        "category": "Normal Tree (పెద్ద చెట్లు / వృక్ష జాతి)",
        "description": "The revered State Tree of Andhra Pradesh; drought-hardy black-trunked fan palm providing food, jaggery, fiber, and construction timber.",
        "native_region": "Coastal Andhra & Rayalaseema",
        "growth_stage": "Perennial Solitary Fan Palm (Up to 100 years)",
        "growing_season": "Summer ice apple and palm sap flush",
        "harvest_season": "Summer Thati Munjalu & Neera sap collection",
        "soil_type": "Deep sandy, loamy and coastal dune soils",
        "temperature_range": "20°C - 45°C",
        "water_requirement": "Very Low once established",
        "sunlight_requirement": "Full Sunlight (8+ hours daily)",
        "fertilizer_recommendation": "None (Self-sufficient on field bunds)",
        "economic_importance": "Official State Tree of AP; sustains rural artisans and toddy/jaggery tappers.",
        "common_uses": ["Refreshing Thati Munjalu (Ice Apples)", "Healthy Palm Jaggery (Thati Bellam)", "Cyclone-resistant Thatch & Timber"],
        "common_diseases": ["Bud Rot", "Black Scorch"],
        "common_pests": ["Rhinoceros Beetle", "Red Palm Weevil"]
    },

    # ==================== COMMERCIAL FRUIT & PLANTATION TREES ====================
    "cashew": {
        "common_name": "Cashew Tree",
        "regional_names": {
            "te": "జీడిమామిడి (Jeedi Mamidi)",
            "hi": "काजू (Kaju)",
            "ta": "முந்திரி (Munthiri)",
            "kn": "ಗೋಡಂಬಿ (Godambi)",
            "ml": "കശുമാവ് (Kashumaavu)",
            "mr": "काजू (Kaju)"
        },
        "scientific_name": "Anacardium occidentale",
        "family": "Anacardiaceae (Cashew Family)",
        "category": "Commercial Fruit Tree (పండ్ల తోట చెట్టు)",
        "description": "Major commercial plantation tree in Srikakulam and Visakhapatnam red laterite soils, producing high-value cashew nuts and apples.",
        "native_region": "Brazil (Major plantation crop in Coastal AP)",
        "growth_stage": "Orchard Fruit Tree",
        "growing_season": "December - March flowering",
        "harvest_season": "March - May nut harvest",
        "soil_type": "Red sandy loam and laterite soils",
        "temperature_range": "22°C - 38°C",
        "water_requirement": "Low to Moderate",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "NPK 500:125:125g per tree annually",
        "economic_importance": "Export-oriented cashew processing hubs (Palasa cashew industry).",
        "common_uses": ["Export Cashew Kernels", "Cashew Apple Juice", "CNSL Industrial Resin"],
        "common_diseases": ["Dieback", "Anthracnose"],
        "common_pests": ["Tea Mosquito Bug (Helopeltis)", "Root & Stem Borer"]
    },
    "oil_palm": {
        "common_name": "African Oil Palm",
        "regional_names": {
            "te": "ఆయిల్ పామ్ (Oil Palm)",
            "hi": "ऑयल पाम (Oil Palm)",
            "ta": "எண்ணெய் பனை (Ennai Panai)",
            "kn": "ಆಯಿಲ್ ಪಾಮ್ (Oil Palm)",
            "ml": "എണ്ണപ്പന (Ennappana)",
            "mr": "ऑईल पाम (Oil Palm)"
        },
        "scientific_name": "Elaeis guineensis",
        "family": "Arecaceae (Palm Family)",
        "category": "Commercial Plantation Palm (వాణిజ్య తోటల పంట)",
        "description": "High-yielding vegetable oil palm cultivated in West Godavari and Krishna delta irrigated belts.",
        "native_region": "West Africa",
        "growth_stage": "Productive Palm (Produces for 25-30 years)",
        "growing_season": "Year-round fruit bunch maturation",
        "harvest_season": "Fresh Fruit Bunches (FFB) every 12 - 15 days",
        "soil_type": "Deep fertile alluvial and loamy soils with high water table",
        "temperature_range": "24°C - 36°C",
        "water_requirement": "Very High (150-200 L/palm/day drip irrigation)",
        "sunlight_requirement": "Full Sunlight",
        "fertilizer_recommendation": "NPK 1200:600:1800g + 500g MgSO4 per tree/year",
        "economic_importance": "Andhra Pradesh is India's leading producer of crude palm oil.",
        "common_uses": ["Crude Palm Oil (CPO)", "Palm Kernel Oil", "Edible Vanaspati"],
        "common_diseases": ["Basal Stem Rot (Ganoderma)", "Spear Rot"],
        "common_pests": ["Rhinoceros Beetle", "Psychid Caterpillars"]
    },
    "sweet_orange": {
        "common_name": "Sweet Orange / Mosambi",
        "regional_names": {
            "te": "బత్తాయి చెట్టు (Batthayi Chettu)",
            "hi": "मौसंबी (Mosambi)",
            "ta": "சாத்துக்குடி (Saathukudi)",
            "kn": "ಮೋಸಂಬಿ (Mosambi)",
            "ml": "മൊസാമ്പി (Mosambi)",
            "mr": "मोसंबी (Mosambi)"
        },
        "scientific_name": "Citrus sinensis",
        "family": "Rutaceae (Citrus Family)",
        "category": "Commercial Fruit Tree (పండ్ల తోట చెట్టు)",
        "description": "Leading commercial citrus crop of Rayalaseema and Prakasam districts, yielding juicy sweet oranges.",
        "native_region": "Southern China / India",
        "growth_stage": "Productive Orchard Tree",
        "growing_season": "Ambe Bahar & Mrig Bahar flowering",
        "harvest_season": "August - November main crop",
        "soil_type": "Well-drained light alluvial or red sandy loam (pH 6.5 - 7.5)",
        "temperature_range": "20°C - 35°C",
        "water_requirement": "Moderate regular drip irrigation",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "NPK 600:200:400g per tree + Micronutrient sprays",
        "economic_importance": "Rayalaseema sweet orange export to North Indian wholesale markets.",
        "common_uses": ["Fresh Table Juice", "Citrus Vitamin-C Supply", "Juice Processing"],
        "common_diseases": ["Citrus Canker", "Greening (Huanglongbing)", "Gummosis"],
        "common_pests": ["Citrus Psylla", "Leaf Miner", "Fruit Sucking Moth"]
    },
    "acid_lime": {
        "common_name": "Acid Lime / Lemon",
        "regional_names": {
            "te": "నిమ్మ చెట్టు (Nimma Chettu)",
            "hi": "नींबू (Nimbu)",
            "ta": "எலுமிச்சை (Elumichai)",
            "kn": "ನಿಂಬೆ (Nimbe)",
            "ml": "ചെറുനാരങ്ങ (Cherunaranga)",
            "mr": "लिंबू (Limbu)"
        },
        "scientific_name": "Citrus aurantiifolia",
        "family": "Rutaceae (Citrus Family)",
        "category": "Commercial Fruit Tree (పండ్ల తోట చెట్టు)",
        "description": "High-profit thorny citrus tree cultivated across Nellore and Tenali, yielding highly acidic round yellow fruits.",
        "native_region": "Southeast Asia",
        "growth_stage": "Continuous Orchard Bearing",
        "growing_season": "Year-round flowering with summer peak",
        "harvest_season": "Multiple harvests throughout year",
        "soil_type": "Deep well-drained loams (Avoid waterlogged clay)",
        "temperature_range": "20°C - 38°C",
        "water_requirement": "Moderate regular irrigation",
        "sunlight_requirement": "Full Sunlight",
        "fertilizer_recommendation": "NPK 500:200:300g per plant + 25kg FYM",
        "economic_importance": "Major cash earner in Nellore (Gudur lime market).",
        "common_uses": ["Everyday Culinary Juice", "Pickling Industry", "Ayurvedic Detox"],
        "common_diseases": ["Citrus Canker (Xanthomonas)", "Tristeza Virus"],
        "common_pests": ["Leaf Miner", "Lemon Butterfly Caterpillar"]
    },
    "pomegranate": {
        "common_name": "Pomegranate",
        "regional_names": {
            "te": "దానిమ్మ చెట్టు (Danimma Chettu)",
            "hi": "अनार (Anar)",
            "ta": "மாதுளை (Mathulai)",
            "kn": "ದಾಳಿಂಬೆ (Dalimbe)",
            "ml": "മാതളം (Mathalam)",
            "mr": "डाळिंब (Dalimb)"
        },
        "scientific_name": "Punica granatum",
        "family": "Lythraceae (Loosestrife Family)",
        "category": "Commercial Fruit Tree (పండ్ల తోట చెట్టు)",
        "description": "High-value commercial dryland fruit crop grown in Anantapur (Bhagwa variety), famous for ruby-red sweet juicy arils.",
        "native_region": "Central Asia & Mediterranean",
        "growth_stage": "Orchard Fruit Shrub/Tree",
        "growing_season": "Regulated Bahar flowering (Hasth Bahar)",
        "harvest_season": "150 - 180 days after blossom",
        "soil_type": "Deep light loamy or gravelly soil with excellent drainage",
        "temperature_range": "22°C - 38°C",
        "water_requirement": "Low to Moderate drip irrigation",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "NPK 400:200:200g per tree + Boron sprays",
        "economic_importance": "Export-quality premium table fruit earner in Rayalaseema.",
        "common_uses": ["Fresh Ruby Arils", "Juice Export", "Astringent Peel Medicine"],
        "common_diseases": ["Bacterial Blight (Telya)", "Cercospora Fruit Spot"],
        "common_pests": ["Anar Butterfly (Deudorix isocrates)", "Thrips"]
    },
    "custard_apple": {
        "common_name": "Custard Apple / Sugar Apple",
        "regional_names": {
            "te": "సీతాఫలం చెట్టు (Sitaphalam Chettu)",
            "hi": "शरीफा / सीताफल (Sharifa)",
            "ta": "சீதாப்பழம் (Seethappazham)",
            "kn": "ಸೀತಾಫಲ (Seethaphala)",
            "ml": "ആത്തച്ചക്ക (Aathachakka)",
            "mr": "सीताफळ (Sitaphal)"
        },
        "scientific_name": "Annona squamosa",
        "family": "Annonaceae (Custard Apple Family)",
        "category": "Commercial Fruit Tree (పండ్ల తోట చెట్టు)",
        "description": "Hardy drought-tolerant dryland tree bearing sweet creamy textured fruits with knobby green skin in autumn.",
        "native_region": "Tropical Americas (Naturalized in AP)",
        "growth_stage": "Small Dryland Orchard Tree",
        "growing_season": "Monsoon vegetative flush",
        "harvest_season": "September - November",
        "soil_type": "Rocky, gravelly, dry marginal soils",
        "temperature_range": "20°C - 40°C",
        "water_requirement": "Low",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "15kg Farmyard manure per tree before monsoon",
        "economic_importance": "Popular seasonal fruit market and pulp processing industry.",
        "common_uses": ["Sweet Autumn Table Fruit", "Ice Cream & Pulp Flavoring", "Insecticidal Seed Oil"],
        "common_diseases": ["Anthracnose", "Alternaria Spot"],
        "common_pests": ["Mealybugs (Pseudococcus)"]
    },
    "jackfruit": {
        "common_name": "Jackfruit Tree",
        "regional_names": {
            "te": "పనస చెట్టు (Panasa Chettu)",
            "hi": "कटहल (Kathal)",
            "ta": "பலா மரம் (Palaa)",
            "kn": "ಹಲಸಿನ ಮರ (Halasina Mara)",
            "ml": "പ്ലാവ് (Plaavu)",
            "mr": "फणस (Fanas)"
        },
        "scientific_name": "Artocarpus heterophyllus",
        "family": "Moraceae (Mulberry Family)",
        "category": "Normal Tree (పెద్ద చెట్లు / వృక్ష జాతి)",
        "description": "Massive evergreen tree producing colossal knobby fruits directly from the trunk and mature limbs (cauliflory).",
        "native_region": "Western Ghats & South Asia",
        "growth_stage": "Colossal Long-lived Evergreen Fruit Tree",
        "growing_season": "Winter flowering",
        "harvest_season": "March - July mature fruit harvest",
        "soil_type": "Deep well-drained fertile alluvial and red loam soils",
        "temperature_range": "22°C - 38°C",
        "water_requirement": "Moderate",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "NPK 600:300:600g per mature tree + 25kg FYM",
        "economic_importance": "Culinary delicacy and heavy golden-yellow timber.",
        "common_uses": ["Panasa Pottu Traditional Curry", "Ripe Sweet Flakes", "Furniture Timber"],
        "common_diseases": ["Rhizopus Soft Rot", "Pink Disease"],
        "common_pests": ["Shoot & Fruit Borer", "Spittlebugs"]
    },
    "amla": {
        "common_name": "Indian Gooseberry / Amla",
        "regional_names": {
            "te": "ఉసిరి చెట్టు (Usiri Chettu)",
            "hi": "आंवला (Amla)",
            "ta": "நெல்லிக்காய் (Nellikai)",
            "kn": "ನೆಲ್ಲಿಕಾಯಿ (Nellikayi)",
            "ml": "നെല്ലി (Nelli)",
            "mr": "आवळा (Aawla)"
        },
        "scientific_name": "Phyllanthus emblica",
        "family": "Phyllanthaceae (Gooseberry Family)",
        "category": "Commercial Fruit Tree (పండ్ల తోట చెట్టు)",
        "description": "Deciduous medicinal fruit tree producing translucent green vitamin-C rich round fruits, highly revered in Karthika Masam.",
        "native_region": "Indian Subcontinent",
        "growth_stage": "Medium Deciduous Fruit Tree",
        "growing_season": "Monsoon flush",
        "harvest_season": "November - January winter harvest",
        "soil_type": "Tolerates sodic, saline, light clay and marginal soils (pH 6.5 - 8.5)",
        "temperature_range": "15°C - 45°C",
        "water_requirement": "Low to Moderate",
        "sunlight_requirement": "Full Sunlight",
        "fertilizer_recommendation": "NPK 400:200:400g per tree + 15kg FYM + Borax",
        "economic_importance": "Premier raw material for Ayurvedic Chyawanprash and hair oils.",
        "common_uses": ["Usirikaya Pachadi (Iconic Pickle)", "Ayurvedic Immunity Rejuvenator", "Karthika Vana Samaradhana Tree"],
        "common_diseases": ["Amla Rust (Ravenelia)", "Internal Fruit Necrosis (Boron deficiency)"],
        "common_pests": ["Bark Eating Caterpillar", "Shoot Gall Maker"]
    },

    # ==================== PRIMARY FIELD CROPS ====================
    "tobacco": {
        "common_name": "Tobacco (FCV)",
        "regional_names": {
            "te": "పొగాకు (Pogaku)",
            "hi": "तम्बाकू (Tambaku)",
            "ta": "புகையிலை (Pugaiyilai)",
            "kn": "ತಂಬಾಕು (Tambaku)",
            "ml": "പുകയില (Pukayila)",
            "mr": "तंबाखू (Tambakhu)"
        },
        "scientific_name": "Nicotiana tabacum",
        "family": "Solanaceae (Nightshade Family)",
        "category": "Commercial Cash Crop (వాణిజ్య పంట)",
        "description": "Commercial cash crop grown in light soils of Prakasam and Guntur for international export flue-cured Virginia leaf.",
        "native_region": "Americas (FCV belt in Andhra)",
        "growth_stage": "Vegetative Leaf Expansion & Topping",
        "growing_season": "Rabi (October - February)",
        "harvest_season": "Priming leaves every 5-7 days for barn curing",
        "soil_type": "Light sandy loam and red sandy soils (Avoid high chlorides)",
        "temperature_range": "20°C - 32°C",
        "water_requirement": "Moderate",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "NPK 40:60:80 kg/ha using Potassium Sulfate (SOP)",
        "economic_importance": "Billion-dollar foreign exchange export crop for Andhra farmers.",
        "common_uses": ["Flue-cured Tobacco Export", "Nicotine Extraction", "Cigarette Manufacturing"],
        "common_diseases": ["Black Shank", "Frog Eye Leaf Spot", "Tobacco Mosaic Virus (TMV)"],
        "common_pests": ["Tobacco Caterpillar (Spodoptera litura)", "Aphids"]
    },
    "red_gram": {
        "common_name": "Red Gram / Pigeon Pea",
        "regional_names": {
            "te": "కందులు (Kandulu)",
            "hi": "अरहर / तुअर (Arhar)",
            "ta": "துவரம் பருப்பு (Thuvarai)",
            "kn": "ತೊಗರಿ (Togari)",
            "ml": "തുവര (Thuvara)",
            "mr": "तूर (Tur)"
        },
        "scientific_name": "Cajanus cajan",
        "family": "Fabaceae (Legume Family)",
        "category": "Pulse Crop (పప్పుధాన్యాల పంట)",
        "description": "Essential pulse crop cultivated across Rayalaseema and coastal tracts as sole crop and intercrop in cotton/groundnut.",
        "native_region": "India",
        "growth_stage": "Long-duration Deep-rooted Legume (150-180 days)",
        "growing_season": "Kharif sowing (June - July)",
        "harvest_season": "December - January",
        "soil_type": "Deep well-drained loams and black soils",
        "temperature_range": "20°C - 35°C",
        "water_requirement": "Low to Moderate (Deep taproot drought survival)",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "NPK 20:50:20 kg/ha with Rhizobium inoculation",
        "economic_importance": "Primary protein pulse for Andhra Pappu and Sambar.",
        "common_uses": ["Toor Dal for Everyday Pappu", "Soil Nitrogen Enrichment", "Fuelwood Stalks"],
        "common_diseases": ["Fusarium Wilt", "Sterility Mosaic Disease (SMD)"],
        "common_pests": ["Gram Pod Borer (Helicoverpa armigera)", "Plume Moth"]
    },
    "black_gram": {
        "common_name": "Black Gram / Urad Dal",
        "regional_names": {
            "te": "మినుములు (Minumulu)",
            "hi": "उड़द दाल (Urad)",
            "ta": "உளுந்து (Ulundu)",
            "kn": "ಉದ್ದು (Uddu)",
            "ml": "ഉഴുന്ന് (Uzhunnu)",
            "mr": "उडीद (Udid)"
        },
        "scientific_name": "Vigna mungo",
        "family": "Fabaceae (Legume Family)",
        "category": "Pulse Crop (పప్పుధాన్యాల పంట)",
        "description": "Famous rice-fallow pulse broadcast directly into standing paddy stubbles in Krishna and Godavari deltas.",
        "native_region": "Indian Subcontinent",
        "growth_stage": "Short-duration Legume (70-75 days)",
        "growing_season": "Rabi (Rice fallows) and Kharif",
        "harvest_season": "70 - 75 days after sowing",
        "soil_type": "Clayey black soils retaining moisture",
        "temperature_range": "22°C - 35°C",
        "water_requirement": "Low (Thrives on residual paddy soil moisture)",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "DAP foliar spray at 2% during flowering",
        "economic_importance": "Core staple pulse for world-famous Andhra Idli, Dosa & Minapa Garelu.",
        "common_uses": ["Minapa Pappu for Breakfast Batters", "Nutritious Protein Dal", "Livestock Fodder"],
        "common_diseases": ["Yellow Mosaic Virus (MYMV)", "Powdery Mildew"],
        "common_pests": ["Whitefly (Bemisia tabaci)", "Pod Borers"]
    },
    "finger_millet": {
        "common_name": "Finger Millet / Ragi",
        "regional_names": {
            "te": "రాగులు / చోడులు (Ragulu / Chodulu)",
            "hi": "रागी (Ragi)",
            "ta": "கேழ்வரகு / ராகி (Kezhvaragu)",
            "kn": "ರಾಗಿ (Ragi)",
            "ml": "റಾಗಿ (Ragi)",
            "mr": "नाचणी (Nachani)"
        },
        "scientific_name": "Eleusine coracana",
        "family": "Poaceae (Grass Family)",
        "category": "Nutri-Cereal Millet (సిరిధాన్యాల చిరుధాన్యం)",
        "description": "Calcium-rich ancient super-cereal of Rayalaseema and tribal Agency areas, famous for finger-like seedhead spikes.",
        "native_region": "East Africa & India",
        "growth_stage": "Tillering & Earhead Maturation (95-115 days)",
        "growing_season": "Kharif and Rabi",
        "harvest_season": "100 - 115 days",
        "soil_type": "Red sandy loam, gravelly dry soils",
        "temperature_range": "20°C - 34°C",
        "water_requirement": "Low (Drought resilient)",
        "sunlight_requirement": "Full Sunlight",
        "fertilizer_recommendation": "NPK 40:20:20 kg/ha",
        "economic_importance": "Leading nutrient-dense climate-resilient staple of Andhra Pradesh.",
        "common_uses": ["Traditional Ragi Mudda / Sankati", "Ragi Java (Malt Drink)", "Diabetic Flour"],
        "common_diseases": ["Ragi Blast (Magnaporthe)", "Foot Rot"],
        "common_pests": ["Stem Borer", "Earhead Caterpillars"]
    },
    "sorghum": {
        "common_name": "Sorghum / Jowar",
        "regional_names": {
            "te": "జొన్నలు (Jonnalu)",
            "hi": "ज्वार (Jowar)",
            "ta": "சோளம் (Cholam)",
            "kn": "ಜೋಳ (Jola)",
            "ml": "ചോളം (Cholam)",
            "mr": "ज्वारी (Jwari)"
        },
        "scientific_name": "Sorghum bicolor",
        "family": "Poaceae (Grass Family)",
        "category": "Nutri-Cereal Millet (సిరిధాన్యాల చిరుధాన్యం)",
        "description": "Tall coarse cereal grain adapted to harsh heat and heavy black cotton soils of Rayalaseema and Guntur.",
        "native_region": "Africa / India",
        "growth_stage": "Panicle Emergence & Grain Filling (100-110 days)",
        "growing_season": "Kharif and Rabi",
        "harvest_season": "100 - 110 days",
        "soil_type": "Deep black soils and loams retaining moisture",
        "temperature_range": "22°C - 38°C",
        "water_requirement": "Low to Moderate",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "NPK 80:40:40 kg/ha",
        "economic_importance": "Staple flatbread grain and prime green fodder for cattle.",
        "common_uses": ["Jonna Rotte (Gluten-Free Flatbread)", "Jonna Pelalu", "Dairy Cattle Fodder"],
        "common_diseases": ["Grain Mold", "Sorghum Rust"],
        "common_pests": ["Shoot Fly (Atherigona soccata)", "Stem Borer"]
    },

    # ==================== ICONIC VEGETABLES & SPICES ====================
    "brinjal": {
        "common_name": "Brinjal / Eggplant",
        "regional_names": {
            "te": "వంకాయ (Vankaya - Iconic AP Veg)",
            "hi": "बैंगन (Baingan)",
            "ta": "கத்திரிக்காய் (Kathirikkai)",
            "kn": "ಬದನೆಕಾಯಿ (Badanekayi)",
            "ml": "വഴുതനങ്ങ (Vazhuthananga)",
            "mr": "वांगी (Vangi)"
        },
        "scientific_name": "Solanum melongena",
        "family": "Solanaceae (Nightshade Family)",
        "category": "Fruiting Vegetable (కూరగాయల పంట)",
        "description": "The undisputed King of Andhra vegetables, cultivated in every district (Gutti Vankaya, Ravva Vankaya, White brinjal).",
        "native_region": "Indian Subcontinent",
        "growth_stage": "Branching Bushy Fruiting Stage",
        "growing_season": "Year-round in AP",
        "harvest_season": "55 - 60 days after transplanting; multiple pickings",
        "soil_type": "Deep well-drained fertile loam and black cotton soils",
        "temperature_range": "22°C - 32°C",
        "water_requirement": "Moderate regular drip watering",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "NPK 100:50:50 kg/ha + Neem cake",
        "economic_importance": "Staple commercial vegetable across all Andhra agricultural mandis.",
        "common_uses": ["Gutti Vankaya Kura (Iconic Stuffed Brinjal)", "Vankaya Vepudu", "Vankaya Bajji"],
        "common_diseases": ["Bacterial Wilt (Ralstonia)", "Little Leaf of Brinjal (Phytoplasma)"],
        "common_pests": ["Shoot & Fruit Borer (Leucinodes orbonalis)", "Epilachna Beetle"]
    },
    "okra": {
        "common_name": "Okra / Ladies Finger",
        "regional_names": {
            "te": "బెండకాయ (Bendakaya)",
            "hi": "भिंडी (Bhindi)",
            "ta": "வெண்டைக்காய் (Vendaikkai)",
            "kn": "ಬೆಂಡೆಕಾಯಿ (Bendekayi)",
            "ml": "വെണ്ടയ്ക്ക (Vendakka)",
            "mr": "भेंडी (Bhendi)"
        },
        "scientific_name": "Abelmoschus esculentus",
        "family": "Malvaceae (Mallow Family)",
        "category": "Fruiting Vegetable (కూరగాయల పంట)",
        "description": "Popular warm-season vegetable bearing tender mucilage-rich green pods with beautiful cream hibiscus-like flowers.",
        "native_region": "South Asia & Africa",
        "growth_stage": "Rapid Continuous Podding",
        "growing_season": "Kharif and Summer",
        "harvest_season": "Pods harvested every alternate day from 45 days onwards",
        "soil_type": "Loose well-drained fertile loam",
        "temperature_range": "24°C - 35°C",
        "water_requirement": "Moderate regular watering",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "NPK 100:50:50 kg/ha",
        "economic_importance": "Fast cash flow crop for smallholder vegetable farmers.",
        "common_uses": ["Bendakaya Pulusu", "Bendakaya Fry", "Dietary Fiber"],
        "common_diseases": ["Yellow Vein Mosaic Virus (YVMV)", "Enation Leaf Curl"],
        "common_pests": ["Fruit Borer (Earias)", "Whitefly", "Jassids"]
    },
    "turmeric": {
        "common_name": "Turmeric Crop",
        "regional_names": {
            "te": "పసుపు (Pasupu - Gold of Duggirala)",
            "hi": "हल्दी (Haldi)",
            "ta": "மஞ்சள் (Manjal)",
            "kn": "ಅರಿಶಿನ (Arishina)",
            "ml": "മഞ്ഞൾ (Manjal)",
            "mr": "हळद (Halad)"
        },
        "scientific_name": "Curcuma longa",
        "family": "Zingiberaceae (Ginger Family)",
        "category": "Rhizome Spice Crop (మసాలా పంట)",
        "description": "Golden sacred spice crop with Duggirala in Guntur district being Asia's renowned trading capital for high-curcumin turmeric.",
        "native_region": "India",
        "growth_stage": "Rhizome Bulking & Maturation (9 months)",
        "growing_season": "Sown in June - July",
        "harvest_season": "February - March",
        "soil_type": "Loose, friable rich loamy soil with excellent drainage",
        "temperature_range": "20°C - 35°C",
        "water_requirement": "High (15-20 irrigations)",
        "sunlight_requirement": "Partial to Full Sunlight",
        "fertilizer_recommendation": "NPK 120:60:120 kg/ha + 25t FYM",
        "economic_importance": "Core commercial export spice of Andhra Pradesh.",
        "common_uses": ["Auspicious Pasupu Ceremonies", "Anti-inflammatory Curcumin", "Cooking Spice"],
        "common_diseases": ["Rhizome Rot (Pythium)", "Leaf Spot (Colletotrichum)"],
        "common_pests": ["Shoot Borer", "Rhizome Scale"]
    },
    "roselle": {
        "common_name": "Roselle / Gongura / Red Sorrel",
        "regional_names": {
            "te": "గోంగూర (Gongura - Queen of Andhra Greens)",
            "hi": "अंबारी (Ambari)",
            "ta": "புளிச்சக்கீரை (Pulichakeerai)",
            "kn": "ಪುಂಡಿ ಪಲ್ಯ (Pundi Palya)",
            "ml": "മത്തിപ്പുളി (Mathippuli)",
            "mr": "अंबाडी (Ambadi)"
        },
        "scientific_name": "Hibiscus sabdariffa",
        "family": "Malvaceae (Mallow Family)",
        "category": "Iconic Leafy Vegetable (ఆంధ్రా గౌరవ ఆకుకూర)",
        "description": "The culinary identity of Andhra Pradesh; distinctive tangy sour-leafed subshrub yielding both red-stem and green-stem varieties.",
        "native_region": "India / West Africa",
        "growth_stage": "Leaf Harvesting Flush",
        "growing_season": "Year-round (Best in Kharif and Summer)",
        "harvest_season": "Leaves clipped every 20-30 days",
        "soil_type": "Rich sandy loam to black fertile soils",
        "temperature_range": "20°C - 35°C",
        "water_requirement": "Moderate",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "NPK 40:20:20 kg/ha + Vermicompost",
        "economic_importance": "Iconic culinary trademark exported globally as Andhra Gongura Pachadi.",
        "common_uses": ["Gongura Pachadi (Andhra Pickle)", "Gongura Mamsam / Royyalu", "Gongura Pappu"],
        "common_diseases": ["Downy Mildew", "Stem Rot"],
        "common_pests": ["Flea Beetle", "Mealybug"]
    },

    # ==================== SACRED, MEDICINAL & WEEDS ====================
    "nut_grass": {
        "common_name": "Nut Grass / Purple Nutsedge",
        "regional_names": {
            "te": "తుంగ గడ్డి / తుంగ ముస్తలు (Tunga Gaddi)",
            "hi": "मोथा (Motha)",
            "ta": "கோரைப்புல் (Koraipul)",
            "kn": "ಭದ್ರ ಮುಷ್ಠಿ (Bhadra Mushti)",
            "ml": "മുത്തങ്ങ (Muthanga)",
            "mr": "लव्हाळा (Lavhala)"
        },
        "scientific_name": "Cyperus rotundus",
        "family": "Cyperaceae (Sedge Family)",
        "category": "Agricultural Weed (పొలాల కలుపు గడ్డి)",
        "description": "Persistent perennial sedge spreading rapidly through chains of underground nutty tubers across cotton and paddy fields.",
        "native_region": "Global Tropics",
        "growth_stage": "Aggressive Tuberous Sedge",
        "growing_season": "Year-round",
        "harvest_season": "Weed eradication target",
        "soil_type": "All soil types",
        "temperature_range": "15°C - 45°C",
        "water_requirement": "Low to High",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Eradication by summer deep tillage to desiccate tubers",
        "economic_importance": "Depletes crop nutrients; tubers hold valuable Musta essential oil for fevers.",
        "common_uses": ["Ayurvedic Musta Medicine for Digestive Fevers", "Weed Management Target"],
        "common_diseases": ["Rust"],
        "common_pests": ["Bactra Moth (Biocontrol)"]
    },
    "bermuda_grass": {
        "common_name": "Bermuda Grass / Scutch Grass",
        "regional_names": {
            "te": "గరిక గడ్డి (Garika Gaddi - Sacred Ganesha Grass)",
            "hi": "दूब घास (Doob)",
            "ta": "அருகம்புல் (Arugampul)",
            "kn": "ಗರಿಕೆ ಹುಲ್ಲು (Garike Hullu)",
            "ml": "കറുകപ്പുല്ല് (Karukappullu)",
            "mr": "दुर्वा (Durva)"
        },
        "scientific_name": "Cynodon dactylon",
        "family": "Poaceae (Grass Family)",
        "category": "Perennial Grass & Sacred Herb (పవిత్ర గడ్డి జాతి)",
        "description": "Hardy stoloniferous mat-forming perennial grass, sacred to Lord Ganesha and premier soil binder on agricultural bunds.",
        "native_region": "Old World",
        "growth_stage": "Stoloniferous Creeping Grass",
        "growing_season": "Year-round",
        "harvest_season": "Continual grazing or ritual clipping",
        "soil_type": "All soil types; highly salt tolerant",
        "temperature_range": "15°C - 45°C",
        "water_requirement": "Low (Extremely drought hardy)",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "None",
        "economic_importance": "Nutritious pasture grass, bund erosion control, and sacred offering.",
        "common_uses": ["Sacred Ganesha 21-Durva Archana", "Bund Soil Conservation", "Nutritious Cattle Grazing"],
        "common_diseases": ["Smut", "Brown Patch"],
        "common_pests": ["Armyworms"]
    }
}
