from datetime import timezone
"""
Botanical knowledge repository for Plant Identification Service.
Provides comprehensive agronomic and botanical metadata for crops, fruits, vegetables, flowers, trees, weeds, and medicinal plants.
Includes native language translations for South Indian regional farmers (Telugu, Tamil, Malayalam, Kannada, Marathi, Hindi).
Covers all broadleaf, grassy, sedge, and aquatic agricultural weed varieties.
"""

PLANT_DATABASE = {
    # ==================== CROPS ====================
    "rice": {
        "common_name": "Rice / Paddy Crop",
        "regional_names": {
            "te": "వరి (Vari)",
            "ta": "நெல் (Nel)",
            "ml": "നെല്ല് (Nellu)",
            "kn": "అక్కి / భత్త (Akki)",
            "mr": "तांदूळ (Tandul)",
            "hi": "धान / चावल (Dhan)"
        },
        "scientific_name": "Oryza sativa",
        "family": "Paddy Cereal Crop",
        "category": "Cereal Grain Crop",
        "description": "Primary staple food crop cultivated across South India in flooded paddies and aerobic soils.",
        "native_region": "South Asia & Tropical Asia",
        "growth_stage": "Tillering & Panicle Initiation",
        "growing_season": "Kharif & Rabi Seasons",
        "harvest_season": "100 - 145 days after sowing",
        "soil_type": "Clay loam or heavy clay retaining moisture (pH 5.5 - 6.5)",
        "temperature_range": "22°C - 34°C",
        "water_requirement": "Flooded paddy or Alternate Wetting & Drying (AWD)",
        "sunlight_requirement": "Full Sun (6 to 8 hours daily)",
        "fertilizer_recommendation": "NPK 120:60:60 kg/ha split application of Urea & MOP Potash",
        "economic_importance": "Primary staple crop for 80%+ of South Indian farming families.",
        "common_uses": ["Steamed grain staple", "Rice flour & parboiled rice", "Paddy straw fodder"],
        "common_diseases": ["Rice Blast", "Bacterial Leaf Blight", "Sheath Blight", "Brown Spot"],
        "common_pests": ["Yellow Stem Borer", "Brown Planthopper (BPH)", "Gall Midge"]
    },
    "paddy": {
        "common_name": "Rice / Paddy Crop",
        "regional_names": {
            "te": "వరి (Vari)",
            "ta": "நெல் (Nel)",
            "ml": "നെല്ല് (Nellu)",
            "kn": "అక్కి / భత్త (Akki)",
            "mr": "तांदूळ (Tandul)",
            "hi": "धान / चावल (Dhan)"
        },
        "scientific_name": "Oryza sativa",
        "family": "Paddy Cereal Crop",
        "category": "Cereal Grain Crop",
        "description": "Primary staple food crop cultivated across South India in flooded paddies and aerobic soils.",
        "native_region": "South Asia & Tropical Asia",
        "growth_stage": "Tillering & Panicle Initiation",
        "growing_season": "Kharif & Rabi Seasons",
        "harvest_season": "100 - 145 days after sowing",
        "soil_type": "Clay loam or heavy clay retaining moisture (pH 5.5 - 6.5)",
        "temperature_range": "22°C - 34°C",
        "water_requirement": "Flooded paddy or Alternate Wetting & Drying (AWD)",
        "sunlight_requirement": "Full Sun (6 to 8 hours daily)",
        "fertilizer_recommendation": "NPK 120:60:60 kg/ha split application of Urea & MOP Potash",
        "economic_importance": "Primary staple crop for 80%+ of South Indian farming families.",
        "common_uses": ["Steamed grain staple", "Rice flour & parboiled rice", "Paddy straw fodder"],
        "common_diseases": ["Rice Blast", "Bacterial Leaf Blight", "Sheath Blight", "Brown Spot"],
        "common_pests": ["Yellow Stem Borer", "Brown Planthopper (BPH)", "Gall Midge"]
    },
    "ragi": {
        "common_name": "Finger Millet / Ragi",
        "regional_names": {
            "te": "రాగులు / చోడులు (Ragulu)",
            "ta": "கேழ்வரகு / ராகி (Kelvaragu)",
            "ml": "പഞ്ചപ്പുല്ല് / രാഗി (Panchappullu)",
            "kn": "రాగి (Ragi)",
            "mr": "नाचणी (Nachani)",
            "hi": "రాగి / మండువా (Ragi)"
        },
        "scientific_name": "Eleusine coracana",
        "family": "Nutri-Cereal Millet",
        "category": "Millet Crop",
        "description": "Highly nutritious, drought-hardy South Indian staple rich in calcium, iron, and fiber.",
        "native_region": "Ethiopian & Indian Highlands",
        "growth_stage": "Tillering & Earhead Flowering",
        "growing_season": "Monsoon / Rainfed Season",
        "harvest_season": "90 - 110 days",
        "soil_type": "Free-draining loamy & red soils (pH 5.0 - 7.0)",
        "temperature_range": "20°C - 32°C",
        "water_requirement": "Low water requirement (Drought resilient)",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Organic FYM compost + NPK 40:20:20 kg/ha",
        "economic_importance": "Superfood millet essential for dryland South Indian farmers.",
        "common_uses": ["Ragi malt beverage", "Ragi mudde / ball", "Ragi roti & dosa", "Health porridge"],
        "common_diseases": ["Ragi Blast (Pyricularia)", "Band Leaf & Sheath Blight"],
        "common_pests": ["Pink Stem Borer", "Earhead Caterpillar", "Aphids"]
    },
    "sugarcane": {
        "common_name": "Sugarcane Crop",
        "regional_names": {
            "te": "చెరకు (Cheruku)",
            "ta": "கரும்பு (Karumbu)",
            "ml": "കരിമ്പ് (Karimbu)",
            "kn": "కబ్బూ (Kabbu)",
            "mr": "ऊस (Uus)",
            "hi": "గన్నా (Ganna)"
        },
        "scientific_name": "Saccharum officinarum",
        "family": "Commercial Cash Crop",
        "category": "Sugar & Cash Crop",
        "description": "High-value commercial cash crop cultivated extensively for sugar and jaggery production.",
        "native_region": "South & Southeast Asia",
        "growth_stage": "Grand Growth & Cane Elongation",
        "growing_season": "Perennial / Annual Crop",
        "harvest_season": "10 - 14 months",
        "soil_type": "Deep well-drained loams & heavy clay soils (pH 6.5 - 7.5)",
        "temperature_range": "25°C - 38°C",
        "water_requirement": "High irrigation via drip or furrow systems",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "NPK 250:100:120 kg/ha with Zinc & Iron foliar sprays",
        "economic_importance": "Major industrial cash crop for sugar mills and bioethanol distillation.",
        "common_uses": ["Refined sugar & jaggery (Gud)", "Fresh sugarcane juice", "Bagasse biofuel"],
        "common_diseases": ["Red Rot", "Smut", "Wilt", "Grassy Shoot Disease"],
        "common_pests": ["Early Shoot Borer", "Top Shoot Borer", "Pyrilla", "Whitefly"]
    },

    # ==================== BROADLEAF & AGGRESSIVE WEEDS ====================
    "parthenium": {
        "common_name": "Parthenium Weed / Congress Grass",
        "regional_names": {
            "te": "పార్థీనియం / వయ్యారి భామ (Parthenium)",
            "ta": "கோபக் கீரை / காங்கிரசு புல் (Parthenium)",
            "ml": "പാർത്ഥീനിയം (Parthenium)",
            "kn": "కాంగ్రెస్ గిడ (Parthenium)",
            "mr": "गाजर गवत (Gajar Gavat)",
            "hi": "గాజర్ ఘాస్ (Gajar Ghas)"
        },
        "scientific_name": "Parthenium hysterophorus",
        "family": "Invasive Agricultural Weed",
        "category": "Harmful Agricultural Weed",
        "description": "Highly aggressive invasive weed that suppresses crop growth, depletes soil nutrients, and causes skin/respiratory allergies.",
        "native_region": "Tropical Americas",
        "growth_stage": "Rapid Flowering & Seed Production",
        "growing_season": "Year-round opportunistic weed",
        "harvest_season": "N/A (Weed target for eradication)",
        "soil_type": "Thrives on all dry, disturbed, or rainfed farm soils",
        "temperature_range": "15°C - 42°C",
        "water_requirement": "Extremely drought tolerant",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Eradication: Spray Glyphosate or 20% Common Salt solution before flowering",
        "economic_importance": "Harmful weed causing up to 40% yield loss in dryland crops.",
        "common_uses": ["No commercial uses — Eradicate immediately to protect crop health"],
        "common_diseases": ["Parthenium Rust Fungus (Biocontrol agent)"],
        "common_pests": ["Zygogramma bicolorata (Mexican Beetle - Natural biocontrol agent)"]
    },
    "lantana": {
        "common_name": "Lantana Weed / Unni Chettu",
        "regional_names": {
            "te": "ఉన్ని చెట్టు / తలంబ్రాల చెట్టు (Lantana)",
            "ta": "உன்னிச் செடி (Unni)",
            "ml": "അരിപ്പൂച്ചെടി (Arippoo)",
            "kn": "లంతాన గిడ (Lantana)",
            "mr": "घाणेरी (Ghaneri)",
            "hi": "రాయ్ మునియా (Rai Munia)"
        },
        "scientific_name": "Lantana camara",
        "family": "Shrubby Broadleaf Weed",
        "category": "Toxic Shrub Weed",
        "description": "Toxic shrub weed forming impenetrable thickets in pastures, orchards, and forest boundaries.",
        "native_region": "Tropical America",
        "growth_stage": "Perennial Shrub Flowering",
        "growing_season": "Year-round",
        "harvest_season": "N/A (Eradicate)",
        "soil_type": "Adaptable to dry red soil, gravel, and wasteland",
        "temperature_range": "15°C - 45°C",
        "water_requirement": "Extremely drought resistant",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Mechanical uprooting or 2,4-D amine herbicide spray on fresh cut stumps",
        "economic_importance": "Toxic to cattle & goats; invades mango, cashew & coconut orchards.",
        "common_uses": ["Eradicate — Toxic to livestock"],
        "common_diseases": ["Lantana Dieback"],
        "common_pests": ["Teleonemia scrupulosa (Lantana Bug biocontrol)"]
    },
    "amaranthus_weed": {
        "common_name": "Wild Amaranth Weed / Thotakura Weed",
        "regional_names": {
            "te": "పిచ్చి తోటకూర గడ్డి (Wild Amaranth)",
            "ta": "குப்பைக் கீரை (Kuppai Keerai)",
            "ml": "കാട്ടു ചീര (Kattu Cheera)",
            "kn": "ముళ్ళ దంటిನ గిడ (Mulla Danti)",
            "mr": "माठ गवत (Math)",
            "hi": "జంగ్లీ చౌలాయీ (Jungli Chaulai)"
        },
        "scientific_name": "Amaranthus viridis",
        "family": "Broadleaf Field Weed",
        "category": "Agricultural Broadleaf Weed",
        "description": "Fast-growing broadleaf weed that competes with cotton, chilli, groundnut, and vegetable crops for soil nitrogen.",
        "native_region": "Tropical South America & Asia",
        "growth_stage": "Vegetative Seed Set",
        "growing_season": "Kharif & Summer",
        "harvest_season": "N/A (Weed control)",
        "soil_type": "Rich fertile farm loams",
        "temperature_range": "20°C - 38°C",
        "water_requirement": "Moderate",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Manual hand weeding or pre-emergence Pendimethalin spray",
        "economic_importance": "Reduces crop growth by robbing soil nitrogen.",
        "common_uses": ["Remove before seed formation"],
        "common_diseases": ["White Blister Rust"],
        "common_pests": ["Amaranthus Stem Weevil"]
    },
    "chenopodium": {
        "common_name": "Bathua Weed / Pigweed",
        "regional_names": {
            "te": "పప్పుకూర పిచ్చి ఆకు (Bathua)",
            "ta": "பருப்புக் கீரை புல் (Bathua)",
            "ml": "വാസ്തു ചീര (Vastu Cheera)",
            "kn": "కాడు సమరసే గిడ (Kadu)",
            "mr": "चाकवत (Chakwat)",
            "hi": "బథువా (Bathua)"
        },
        "scientific_name": "Chenopodium album",
        "family": "Broadleaf Winter Weed",
        "category": "Agricultural Broadleaf Weed",
        "description": "Common winter broadleaf weed in wheat, mustard, onion, and vegetable fields.",
        "native_region": "Europe & Asia",
        "growth_stage": "Vegetative Leaf Expansion",
        "growing_season": "Rabi / Winter Season",
        "harvest_season": "N/A (Weed target)",
        "soil_type": "Nitrogen-rich farm soils",
        "temperature_range": "10°C - 25°C",
        "water_requirement": "Moderate",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Post-emergence 2,4-D ethyl ester or manual hoeing",
        "economic_importance": "Depletes soil moisture in winter crops.",
        "common_uses": ["Edible young green leaves (Bathua saag)"],
        "common_diseases": ["Downy Mildew of Chenopodium"],
        "common_pests": ["Aphids", "Leaf Miner"]
    },
    "portulaca": {
        "common_name": "Purslane / Ganga Payala Weed",
        "regional_names": {
            "te": "గంగ పాయల ఆకు / పప్పుకూర మొక్క (Purslane)",
            "ta": "பருப்புக் கீரை (Paruppu Keerai)",
            "ml": "കൊഴുപ്പ (Kozhuppa)",
            "kn": "గోణి గిడ (Goni Gida)",
            "mr": "घोळ (Ghol)",
            "hi": "కూల్ఫా (Kulfa)"
        },
        "scientific_name": "Portulaca oleracea",
        "family": "Succulent Broadleaf Weed",
        "category": "Agricultural Broadleaf Weed",
        "description": "Mat-forming succulent weed with reddish stems that thrives in irrigated vegetable plots and orchards.",
        "native_region": "Old World Tropics",
        "growth_stage": "Prostrate Mat Expansion",
        "growing_season": "Summer & Rainy Season",
        "harvest_season": "N/A",
        "soil_type": "Sandy or loamy irrigated soils",
        "temperature_range": "20°C - 40°C",
        "water_requirement": "Highly drought tolerant succulent",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Shallow cultivation or mulching between crop rows",
        "economic_importance": "Competes with shallow-rooted vegetable crops.",
        "common_uses": ["Edible Omega-3 rich leafy herb"],
        "common_diseases": ["Dichotomophthora Leaf Spot"],
        "common_pests": ["Portulaca Leaf Miner"]
    },

    # ==================== SEDGE & GRASS WEEDS ====================
    "cyperus": {
        "common_name": "Nut Grass / Tunga Weed",
        "regional_names": {
            "te": "తుంగ గడ్డి (Tunga Gaddi)",
            "ta": "கோரை புல் (Korai Pul)",
            "ml": "മുത്തങ്ങ (Muthanga)",
            "kn": "ముస్తె గిడ (Muste)",
            "mr": "नागरमोथा (Nagarmotha)",
            "hi": "మోతా గస్ (Motha)"
        },
        "scientific_name": "Cyperus rotundus",
        "family": "Perennial Sedge Weed",
        "category": "Harmful Sedge Weed",
        "description": "Perennial sedge weed with underground nut tubers, considered one of the world's worst agricultural weeds.",
        "native_region": "Africa & Southern Asia",
        "growth_stage": "Tuberous Sprouting & Foliage Growth",
        "growing_season": "Year-round weed",
        "harvest_season": "N/A (Target for eradication)",
        "soil_type": "Moist, clay, or loamy soil",
        "temperature_range": "15°C - 40°C",
        "water_requirement": "Tolerates both wet paddies and drought",
        "sunlight_requirement": "Full Sun to Partial Shade",
        "fertilizer_recommendation": "Control: Apply Halosulfuron-methyl 75% WG or Glyphosate systemic herbicide",
        "economic_importance": "Competes fiercely with sugarcane, cotton, and vegetable crops for soil nutrients.",
        "common_uses": ["Traditional Ayurvedic oil extraction (Nagarmotha)"],
        "common_diseases": ["Fungal Rust (Puccinia cyperi)"],
        "common_pests": ["Bactra verutana (Sedge Moth)"]
    },
    "bermuda_grass": {
        "common_name": "Bermuda Grass / Garika Gaddi",
        "regional_names": {
            "te": "గరిక గడ్డి (Garika Gaddi)",
            "ta": "அறுகம்புல் (Arugampul)",
            "ml": "കറുക പുല്ല് (Karuka)",
            "kn": "గరికె గిడ (Garike)",
            "mr": "दुर्वा (Durva)",
            "hi": "దూబ్ ఘాస్ (Doob Ghas)"
        },
        "scientific_name": "Cynodon dactylon",
        "family": "Creeping Perennial Grass",
        "category": "Pasture Grass & Weed",
        "description": "Fast-spreading creeping stoloniferous grass used as livestock fodder, lawn grass, and sacred medicinal herb.",
        "native_region": "Middle East & Indian Subcontinent",
        "growth_stage": "Stoloniferous Creeping Mat",
        "growing_season": "Year-round",
        "harvest_season": "Continuous cutting",
        "soil_type": "Adaptable to all soil types (pH 5.5 - 8.5)",
        "temperature_range": "15°C - 40°C",
        "water_requirement": "Drought tolerant once rooted",
        "sunlight_requirement": "Full Direct Sun",
        "fertilizer_recommendation": "Responds well to organic FYM and nitrogen topdressing",
        "economic_importance": "Excellent cattle pasture grass and soil erosion control cover.",
        "common_uses": ["Cattle fodder grass", "Lawn turf", "Ayurvedic herbal juice", "Erosion control"],
        "common_diseases": ["Bermuda Grass Smut", "Bipolaris Leaf Spot"],
        "common_pests": ["Armyworms", "Bermudagrass Mite"]
    },
    "echinochloa": {
        "common_name": "Barnyard Grass / Oora Gaddi (Paddy Weed)",
        "regional_names": {
            "te": "ఊర గడ్డి / బొంత గడ్డి (Oora Gaddi)",
            "ta": "குதிரைவாலி புல் (Kudiraivali)",
            "ml": "കവട പുല്ല് (Kavada)",
            "kn": "కాడు బరగు గిడ (Kadu Baragu)",
            "mr": "सावा गवत (Sawa)",
            "hi": "సాన్వా ఘాస్ (Sanwa)"
        },
        "scientific_name": "Echinochloa crus-galli",
        "family": "Paddy Field Grassy Weed",
        "category": "Grassy Weed",
        "description": "Major grassy weed in flooded paddy fields mimicking young rice plants.",
        "native_region": "Tropical & Subtropical Asia",
        "growth_stage": "Tillering & Seed Head",
        "growing_season": "Monsoon / Paddy Season",
        "harvest_season": "N/A (Weed control)",
        "soil_type": "Waterlogged clay paddy soil",
        "temperature_range": "20°C - 38°C",
        "water_requirement": "High water requirement",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Pre-emergence Pretilachlor 50% EC spray in flooded paddy 3 days after transplanting",
        "economic_importance": "Causes up to 50% yield reduction in paddy crops if uncontrolled.",
        "common_uses": ["Fodder for cattle when young"],
        "common_diseases": ["Echinochloa Blast"],
        "common_pests": ["Paddy Stem Borer"]
    },
    "digitaria": {
        "common_name": "Crabgrass / Nari Gaddi",
        "regional_names": {
            "te": "నరి గడ్డి / పిచ్చి గడ్డి (Nari Gaddi)",
            "ta": "நரிப் புல் (Nari Pul)",
            "ml": "നരി പുല്ല് (Nari)",
            "kn": "నరి గిడ (Nari Gida)",
            "mr": "खेकडा गवत (Khekada)",
            "hi": "సాంక్రి ఘాస్ (Sankri)"
        },
        "scientific_name": "Digitaria sanguinalis",
        "family": "Annual Grassy Weed",
        "category": "Grassy Weed",
        "description": "Spreading annual grass weed that smothers young maize, sugarcane, groundnut, and cotton seedlings.",
        "native_region": "Europe & Asia",
        "growth_stage": "Spreading Mat",
        "growing_season": "Summer & Rainy Season",
        "harvest_season": "N/A",
        "soil_type": "Sandy or loamy dryland soils",
        "temperature_range": "18°C - 38°C",
        "water_requirement": "Drought tolerant",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Inter-row cultivation or Quizalofop-p-ethyl post-emergence spray",
        "economic_importance": "Reduces early crop seedling vigor.",
        "common_uses": ["Cattle grazing"],
        "common_diseases": ["Helminthosporium Leaf Blight"],
        "common_pests": ["Grasshoppers"]
    },

    # ==================== AQUATIC PADDY WEEDS ====================
    "water_hyacinth": {
        "common_name": "Water Hyacinth / Gurrapu Dekka Weed",
        "regional_names": {
            "te": "గుర్రపు డెక్క / గుర్రం తామర (Gurrapu Dekka)",
            "ta": "ஆகாயத் தாமரை (Agaya Thamarai)",
            "ml": "ആഗായ വാഴ / കുളവാഴ (Kulavazha)",
            "kn": "నీరు తామరె గిడ (Neeru)",
            "mr": "जलकुंभी (Jalkumbhi)",
            "hi": "జలకుంబీ (Jalkumbhi)"
        },
        "scientific_name": "Eichhornia crassipes",
        "family": "Aquatic Invasive Weed",
        "category": "Aquatic Invasive Weed",
        "description": "Floating aquatic weed covering irrigation canals, paddy reservoirs, and farm ponds, choking oxygen and water flow.",
        "native_region": "Amazon Basin, South America",
        "growth_stage": "Floating Bulbous Rosette",
        "growing_season": "Year-round water weed",
        "harvest_season": "N/A (Clear immediately)",
        "soil_type": "Freshwater farm ponds & canals",
        "temperature_range": "15°C - 38°C",
        "water_requirement": "Flooded water body required",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Mechanical removal & bio-composting into organic manure",
        "economic_importance": "Blocks canal irrigation water flow to downstream fields.",
        "common_uses": ["Organic bio-fertilizer compost after shredding"],
        "common_diseases": ["Cercospora rodmanii (Biocontrol fungus)"],
        "common_pests": ["Neochetina eichhorniae (Weevil biocontrol)"]
    },

    # ==================== ANDHRA PRADESH WEED PLANTS ====================
    "trianthema": {
        "common_name": "Desert Horse Purslane / Galijeru",
        "regional_names": {
            "te": "గలిజేరు / తెల్ల గలిజేరు (Galijeru)",
            "ta": "சாரணை (Saranai)",
            "ml": "തഴുതാമ (Thazhuthama)",
            "kn": "ಕೊಮ್ಮೆ ಗಿಡ (Komme Gida)",
            "mr": "विषखापर (Vishkhapar)",
            "hi": "सांठी / विषखपरा (Santhi)"
        },
        "scientific_name": "Trianthema portulacastrum",
        "family": "Aizoaceae (Broadleaf Field Weed)",
        "category": "Agricultural Broadleaf Weed",
        "description": "Aggressive prostrate succulent broadleaf weed rampant in Andhra cotton, chilli, maize, and vegetable black cotton soils.",
        "native_region": "Tropical Americas & Southern Asia",
        "growth_stage": "Prostrate Spreading Mat",
        "growing_season": "Kharif & Summer rainy flush",
        "harvest_season": "N/A (Control before flowering)",
        "soil_type": "Black cotton and sandy loam soils",
        "temperature_range": "22°C - 42°C",
        "water_requirement": "Drought tolerant succulent",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Pre-emergence Pendimethalin 30% EC or early post-emergence Quizalofop / manual weeding",
        "economic_importance": "Chokes young cotton and chilli seedlings, robbing 30%+ of early nitrogen and moisture.",
        "common_uses": ["Traditional liver support medicinal herb in Ayurveda"],
        "common_diseases": ["Cercospora trianthemae Leaf Spot"],
        "common_pests": ["Flea Beetles", "Leaf Caterpillars"]
    },
    "achyranthes": {
        "common_name": "Prickly Chaff Flower / Uttareni",
        "regional_names": {
            "te": "ఉత్తరేణి (Uttareni)",
            "ta": "நாயுருவி (Nayuruvi)",
            "ml": "കടലാടി (Kadaladi)",
            "kn": "ಉತ್ತರಾಣಿ (Uttarani)",
            "mr": "आघाडा (Aghada)",
            "hi": "लटजीरा / चिरचिटा (Latjira)"
        },
        "scientific_name": "Achyranthes aspera",
        "family": "Amaranthaceae (Broadleaf Weed)",
        "category": "Broadleaf Field & Waste Land Weed",
        "description": "Erect stiff herb with prickly hooked burr seeds that cling to farmer clothes and cattle hides across field bunds and drylands.",
        "native_region": "Tropical Asia & Africa",
        "growth_stage": "Erect Spike Flowering",
        "growing_season": "Rainy to Winter season",
        "harvest_season": "N/A (Weed control on bunds)",
        "soil_type": "Dry gravelly, red and wasteland soils",
        "temperature_range": "18°C - 38°C",
        "water_requirement": "Low (Extremely drought hardy)",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Mechanical uprooting along field edges and bunds before spiky seed heads mature",
        "economic_importance": "Invasive on field bunds and borders; irritates livestock.",
        "common_uses": ["Revered Ayurvedic medicinal plant for dental and respiratory remedies"],
        "common_diseases": ["Alternaria Blight"],
        "common_pests": ["Stem Borers", "Mealybugs"]
    },
    "eclipta": {
        "common_name": "False Daisy / Guntagalagaraku",
        "regional_names": {
            "te": "గుంటగలగరాకు (Guntagalagaraku)",
            "ta": "கரிசலாங்கண்ணி (Karisalanganni)",
            "ml": "കയ്യോന്നി (Kayyonni)",
            "kn": "ಗರುಗ ಗಿಡ (Garuga)",
            "mr": "माका (Maka)",
            "hi": "భృంగరాజ్ (Bhringraj)"
        },
        "scientific_name": "Eclipta alba",
        "family": "Asteraceae (Moisture-Loving Weed)",
        "category": "Broadleaf Moisture Weed",
        "description": "Small branched herb with small white daisy-like flowers thriving in wet irrigation channels, paddy field edges, and canal banks.",
        "native_region": "Tropical & Subtropical Asia",
        "growth_stage": "Active Flowering & Seed Head",
        "growing_season": "Year-round in moist soils",
        "harvest_season": "Harvestable for herbal medicine",
        "soil_type": "Wet, puddled, and damp alluvial soil",
        "temperature_range": "18°C - 35°C",
        "water_requirement": "High moisture requirement",
        "sunlight_requirement": "Partial Shade to Full Sun",
        "fertilizer_recommendation": "Easily removed during regular paddy hand-weeding or channel clearing",
        "economic_importance": "Invasive in irrigation drains but highly valuable commercially as herbal hair oil ingredient.",
        "common_uses": ["Premier Ayurvedic hair growth oil ingredient (Bhringraj)"],
        "common_diseases": ["Powdery Mildew of Asteraceae"],
        "common_pests": ["Aphids"]
    },
    "commelina": {
        "common_name": "Benghal Dayflower / Vennedevi Koora",
        "regional_names": {
            "te": "వెన్నెదేవి కూర / అమృతకాడ (Vennedevi Koora)",
            "ta": "கானாங்கோழை (Kanangozhai)",
            "ml": "കണ്ണാന്തളി (Kannanthali)",
            "kn": "ಕನ್ನೆ ಗಿಡ (Kanne Gida)",
            "mr": "केना (Kena)",
            "hi": "కనకౌవా (Kankauwa)"
        },
        "scientific_name": "Commelina benghalensis",
        "family": "Commelinaceae (Fleshy Broadleaf Weed)",
        "category": "Creeping Fleshy Broadleaf Weed",
        "description": "Fleshy creeping weed with brilliant sky-blue flowers that roots at leaf nodes, notorious for surviving normal cultivation in wet soils.",
        "native_region": "Tropical Asia & Africa",
        "growth_stage": "Stoloniferous Creeping & Aerial/Subterranean Flowering",
        "growing_season": "Monsoon / Kharif season",
        "harvest_season": "N/A (Control early)",
        "soil_type": "Moist loamy and clay soils",
        "temperature_range": "20°C - 38°C",
        "water_requirement": "Moderate to High",
        "sunlight_requirement": "Full Sun to Shade",
        "fertilizer_recommendation": "Post-emergence Glyphosate or 2,4-D Na salt in non-crop areas; inter-cultivation in maize/cotton",
        "economic_importance": "Competes with groundnut, maize, and turmeric crops.",
        "common_uses": ["Young leaves consumed as village wild greens; fodder for milch cattle"],
        "common_diseases": ["Rust (Uromyces commelinae)"],
        "common_pests": ["Grasshoppers"]
    },
    "argemone": {
        "common_name": "Mexican Prickly Poppy / Brahmadandi",
        "regional_names": {
            "te": "బ్రహ్మదండి (Brahmadandi)",
            "ta": "பிரம்மத்தண்டு (Brammathandu)",
            "ml": "പൊregularമുള്ള് (Ponnummullu)",
            "kn": "ದತ್ತೂರಿ ಗಿಡ (Datturi)",
            "mr": "धोत्रा / फिरंगी (Dhotra)",
            "hi": "సత్యానాశీ / భట్‌కటయ్యా (Satyanashi)"
        },
        "scientific_name": "Argemone mexicana",
        "family": "Papaveraceae (Prickly Weed)",
        "category": "Invasive Poisonous Broadleaf Weed",
        "description": "Spiny glaucous herb with bright yellow flowers and toxic yellow sap that invades fallow farm lands, dry road margins, and pulse fields.",
        "native_region": "Mexico & Central America",
        "growth_stage": "Spiny Rosette to Flowering",
        "growing_season": "Winter to Summer season",
        "harvest_season": "N/A (Toxic weed)",
        "soil_type": "Dry sandy, degraded and saline soils",
        "temperature_range": "15°C - 42°C",
        "water_requirement": "Very Low (Drought resistant)",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Hand-pull with thick leather gloves before seed capsules rupture",
        "economic_importance": "Seeds contaminate mustard and sesame crops causing dropsy health hazards.",
        "common_uses": ["Strictly non-edible; dangerous seed contaminant"],
        "common_diseases": ["Foliar Blight"],
        "common_pests": ["Capsule Borers"]
    },
    "tridax": {
        "common_name": "Coatbuttons / Gaddi Chamanti",
        "regional_names": {
            "te": "గడ్డి చామంతి / పిచ్చి చామంతి (Gaddi Chamanti)",
            "ta": "வெட்டுக்காயப் பூண்டு (Vettukaya Poondu)",
            "ml": "ചിരവനാക്ക് (Chiravanakku)",
            "kn": "ಜಯಂತಿ ಗಿಡ (Jayanti Gida)",
            "mr": "कंबरमोडी (Kambarmodi)",
            "hi": "ఖల్‌మురియా / జఖమ్‌హయాత్ (Khalmuriya)"
        },
        "scientific_name": "Tridax procumbens",
        "family": "Asteraceae (Daisy Herb Weed)",
        "category": "Broadleaf Field & Orchard Weed",
        "description": "Prostrate creeping daisy weed with yellow-centered creamy florets abundant across field margins, bunds, and dry orchard floors.",
        "native_region": "Tropical Americas",
        "growth_stage": "Sprawling Flowering",
        "growing_season": "Year-round",
        "harvest_season": "N/A",
        "soil_type": "Well-drained sandy, red, and rocky soils",
        "temperature_range": "15°C - 40°C",
        "water_requirement": "Low",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Shallow hoeing or inter-row mulching in fruit orchards",
        "economic_importance": "Minor field competitor; beneficial nectar host for pollinating honeybees.",
        "common_uses": ["Famous village styptic wound-healing leaf paste (Vettukaya)"],
        "common_diseases": ["Leaf Spot"],
        "common_pests": ["Aphids", "Thrips"]
    },
    "acalypha": {
        "common_name": "Indian Acalypha / Muripinda",
        "regional_names": {
            "te": "మురిపిండ / కుప్పింట (Muripinda / Kuppinta)",
            "ta": "குப்பைமேனி (Kuppaimeni)",
            "ml": "കുപ്പമേനി (Kuppameni)",
            "kn": "ಕುಪ್ಪಿ ಗಿಡ (Kuppi Gida)",
            "mr": "खोखली (Khokhali)",
            "hi": "కుప్పీ / ఖోకలీ (Kuppi)"
        },
        "scientific_name": "Acalypha indica",
        "family": "Euphorbiaceae (Annual Herb Weed)",
        "category": "Broadleaf Annual Weed",
        "description": "Erect annual herb with catkin spikes and ovate serrated leaves ubiquitous around farm barns, fences, and irrigated crop beds.",
        "native_region": "Tropical Asia & Africa",
        "growth_stage": "Vegetative Flowering",
        "growing_season": "Monsoon to Winter",
        "harvest_season": "N/A",
        "soil_type": "Moist nutrient-rich loams and compost margins",
        "temperature_range": "18°C - 38°C",
        "water_requirement": "Moderate",
        "sunlight_requirement": "Full Sun to Light Shade",
        "fertilizer_recommendation": "Easily pulled by hand during early row weeding",
        "economic_importance": "Competes in nursery vegetable beds; roots strongly attract domestic cats.",
        "common_uses": ["Renowned Siddha and Ayurvedic skin remedy for ringworm and allergies"],
        "common_diseases": ["Powdery Mildew"],
        "common_pests": ["Spider Mites"]
    },
    "digera": {
        "common_name": "False Amaranth / Chenchali Koora",
        "regional_names": {
            "te": "చెంచలి కూర / చిన్న చెంచలి (Chenchali Koora)",
            "ta": "தொய்யாக் கீரை (Thoyya Keerai)",
            "ml": "ചെഞ്ചലി (Chenchali)",
            "kn": "ಗೋರಿ ಗಿಡ (Gori Gida)",
            "mr": "तांदुळजा (Tandulja)",
            "hi": "లహసువా / లట్మహురియా (Lahsuwa)"
        },
        "scientific_name": "Digera muricata",
        "family": "Amaranthaceae (Annual Broadleaf Weed)",
        "category": "Edible Agricultural Broadleaf Weed",
        "description": "Erect smooth annual herb with pinkish-white flower spikes common in rainfed groundnut, pearl millet, and cotton rows.",
        "native_region": "South Asia & Middle East",
        "growth_stage": "Vegetative to Spike Formation",
        "growing_season": "Kharif rainy season",
        "harvest_season": "Harvested as green leafy vegetable",
        "soil_type": "Sandy, light loamy and red farm soils",
        "temperature_range": "20°C - 38°C",
        "water_requirement": "Low to Moderate",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Uprooted during hand-hoeing; readily cooked by farming families",
        "economic_importance": "Competes for early fertilizer nutrients in rainfed crops if dense.",
        "common_uses": ["Nutritious, iron-rich traditional wild green leafy vegetable"],
        "common_diseases": ["Leaf Blight"],
        "common_pests": ["Flea Beetles"]
    },
    "leucas": {
        "common_name": "Thyme-Leaved Leucas / Thummi Mokka",
        "regional_names": {
            "te": "తుమ్మి మొక్క / తుమ్మి పువ్వు (Thummi Mokka)",
            "ta": "தும்பை (Thumbai)",
            "ml": "തുമ്പ (Thumba)",
            "kn": "ತುಂಬೆ ಗಿಡ (Thumbe Gida)",
            "mr": "तांबोळी (Tamboli)",
            "hi": "గోమా / ఛోటా హల్‌కుసా (Goma)"
        },
        "scientific_name": "Leucas aspera",
        "family": "Lamiaceae (Aromatic Mint Herb Weed)",
        "category": "Aromatic Broadleaf Field Weed",
        "description": "Strongly aromatic annual herb with whorls of pure white woolly flowers seen across post-harvest fallows, dry fields, and bunds.",
        "native_region": "Tropical South Asia & Southeast Asia",
        "growth_stage": "Whorled Flowering",
        "growing_season": "Post-monsoon to Summer",
        "harvest_season": "N/A",
        "soil_type": "Light, sandy, and alluvial field soils",
        "temperature_range": "16°C - 40°C",
        "water_requirement": "Drought hardy",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Easily controlled by light harrowing or inter-cultivation",
        "economic_importance": "Harbors beneficial insects; sacred flower in Andhra rituals.",
        "common_uses": ["Herbal vapor inhalation for head colds and sinus relief"],
        "common_diseases": ["Rust"],
        "common_pests": ["Leaf Rollers"]
    },
    "amaranthus_spinosus": {
        "common_name": "Spiny Amaranth / Mulla Thotakura",
        "regional_names": {
            "te": "ముళ్ల తోటకూర (Mulla Thotakura)",
            "ta": "முள்ளுக் கீரை (Mullu Keerai)",
            "ml": "മുള്ളൻ ചീര (Mullan Cheera)",
            "kn": "ಮುಳ್ಳು ಹರಿವೆ (Mullu Harive)",
            "mr": "काटेमाठ (Katemath)",
            "hi": "కాంటేవాలీ చౌలాయీ (Kante Chaulai)"
        },
        "scientific_name": "Amaranthus spinosus",
        "family": "Amaranthaceae (Thorny Weed)",
        "category": "Thorny Broadleaf Field Weed",
        "description": "Erect rigid weed equipped with sharp needle-like spines at leaf axils, troublesome in grazing pastures and vegetable plots.",
        "native_region": "Tropical Americas",
        "growth_stage": "Thorny Branching to Spike",
        "growing_season": "Kharif & Summer",
        "harvest_season": "N/A (Avoid mature thorns)",
        "soil_type": "Fertile nitrogen-rich field soils",
        "temperature_range": "20°C - 40°C",
        "water_requirement": "Moderate",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Remove while young before sharp axillary spines harden",
        "economic_importance": "Sharp spines injure farm workers' hands during harvest; avoids cattle grazing.",
        "common_uses": ["Young pre-spine tender shoots boiled in dal"],
        "common_diseases": ["White Rust (Albugo)"],
        "common_pests": ["Stem Weevil", "Cutworms"]
    },

    # ==================== ANDHRA PRADESH BIG TREES ====================
    "neem": {
        "common_name": "Neem Tree / Vepa Chettu",
        "regional_names": {
            "te": "వేప చెట్టు (Vepa Chettu)",
            "ta": "வேப்ப மரம் (Veppamaram)",
            "ml": "വേപ്പ് (Vep)",
            "kn": "ಬೇವು (Bevu)",
            "mr": "कडुनिंब (Kadunimb)",
            "hi": "నీమ్ (Neem)"
        },
        "scientific_name": "Azadirachta indica",
        "family": "Meliaceae (Mahogany Family)",
        "category": "Medicinal, Timber & Bio-Pesticide Tree",
        "description": "Venerable drought-hardy native evergreen tree omnipresent across Andhra villages, farms, and field perimeters.",
        "native_region": "Indian Subcontinent & Dry Tropics",
        "growth_stage": "Mature Canopy Tree (Reaches 15-25m)",
        "growing_season": "Year-round evergreen",
        "harvest_season": "Neem seed collection in May - July",
        "soil_type": "Highly adaptable; thrives in rocky, sandy, red and black soils (pH 5.0 - 8.5)",
        "temperature_range": "15°C - 48°C (Extreme heat tolerant)",
        "water_requirement": "Very low once established (Drought resilient)",
        "sunlight_requirement": "Full Direct Sunlight",
        "fertilizer_recommendation": "Organic FYM compost annually around drip line; requires minimal chemicals",
        "economic_importance": "Produces neem oil (Azadirachtin) bio-pesticide, neem seed cake organic fertilizer, termite-resistant timber, and medicinal twigs.",
        "common_uses": ["Natural organic crop bio-pesticide", "Neem cake soil nematicide", "Medicinal dental chew twigs", "Cool shade & breeze"],
        "common_diseases": ["Neem Dieback (Phomopsis azadirachtae)", "Powdery Mildew"],
        "common_pests": ["Tea Mosquito Bug", "Scale Insects"]
    },
    "mango": {
        "common_name": "Mango Tree / Mamidi Chettu",
        "regional_names": {
            "te": "మామిడి చెట్టు (Mamidi Chettu)",
            "ta": "மாமரம் (Maamaram)",
            "ml": "മാവ് (Maavu)",
            "kn": "ಮಾವಿನ ಮರ (Mavina Mara)",
            "mr": "आंबा (Amba)",
            "hi": "ఆమ్ (Aam)"
        },
        "scientific_name": "Mangifera indica",
        "family": "Anacardiaceae (Sumac Family)",
        "category": "Commercial Fruit & Timber Orchard Tree",
        "description": "The king of commercial fruit orchards in Andhra Pradesh, renowned for world-famous cultivars like Banganapalli, Totapuri, Suvarnarekha, and Cherukurasam.",
        "native_region": "Tropical Southern & Eastern Asia",
        "growth_stage": "Flowering / Fruit Development / Flushes",
        "growing_season": "Winter flowering (Jan-Feb); Summer fruiting (April-June)",
        "harvest_season": "100 - 130 days from fruit set",
        "soil_type": "Deep well-drained loamy or red alluvial soil (pH 5.5 - 7.5)",
        "temperature_range": "24°C - 38°C",
        "water_requirement": "Moderate drip irrigation; stress required before winter flowering",
        "sunlight_requirement": "Full Sun (8+ hours daily)",
        "fertilizer_recommendation": "1000g N, 500g P2O5, 1000g K2O per mature tree applied post-harvest + Micronutrient zinc/boron foliar spray",
        "economic_importance": "Core cash orchard crop for lakhs of Andhra farmers; major export crop to Gulf and European markets.",
        "common_uses": ["Fresh table dessert fruit", "Mango pulp processing", "Raw mango pickles (Avakaya)", "Furniture timber"],
        "common_diseases": ["Mango Anthracnose (Colletotrichum)", "Powdery Mildew (Oidium)", "Sooty Mold"],
        "common_pests": ["Mango Hopper", "Fruit Fly (Bactrocera)", "Stem Borer"]
    },
    "guava": {
        "common_name": "Guava Tree / Jama Chettu",
        "regional_names": {
            "te": "జామ చెట్టు (Jama Chettu)",
            "ta": "கொய்யா மரம் (Koyyamaram)",
            "ml": "പേര (Pera)",
            "kn": "ಸೀಬೆ ಮರ (Seebe Mara)",
            "mr": "पेरू (Peru)",
            "hi": "అమరూద్ (Amrood)"
        },
        "scientific_name": "Psidium guajava",
        "family": "Myrtaceae (Myrtle Family)",
        "category": "Fruit Orchard Tree",
        "description": "High-profit perennial fruit tree cultivated extensively in high-density meadow orchards across Andhra (Allahabad Safeda, Lucknow 49, Taiwan White/Pink).",
        "native_region": "Tropical America",
        "growth_stage": "Vegetative Flush, Flowering & Fruit Set",
        "growing_season": "Dual cropping: Mrig Bahar (Winter) & Ambe Bahar (Monsoon)",
        "harvest_season": "90 - 120 days from flowering",
        "soil_type": "Adaptable; deep well-drained loam or clay-loam (pH 6.5 - 7.5)",
        "temperature_range": "20°C - 35°C",
        "water_requirement": "Moderate (Responds excellently to drip irrigation)",
        "sunlight_requirement": "Full Direct Sun",
        "fertilizer_recommendation": "NPK 500:200:500g per mature tree per year + Zinc sulfate spray",
        "economic_importance": "Vitamin C superfood offering steady quarterly income for small and marginal orchard farmers.",
        "common_uses": ["Fresh fruit consumption", "Jams, jellies, and pulp", "Medicinal tannin-rich leaf tea"],
        "common_diseases": ["Guava Wilt (Fusarium oxysporum)", "Anthracnose", "Fruit Canker"],
        "common_pests": ["Fruit Fly", "Tea Mosquito Bug", "Mealybug"]
    },
    "tamarind": {
        "common_name": "Tamarind Tree / Chinta Chettu",
        "regional_names": {
            "te": "చింత చెట్టు (Chinta Chettu)",
            "ta": "புளிய மரம் (Puliyamaram)",
            "ml": "പുളി (Puli)",
            "kn": "ಹುಣಸೆ ಮರ (Hunase Mara)",
            "mr": "चिंच (Chinch)",
            "hi": "ఇమ్లీ (Imli)"
        },
        "scientific_name": "Tamarindus indica",
        "family": "Fabaceae (Legume Family)",
        "category": "Fruit, Spice & Heavy Timber Tree",
        "description": "Long-lived massive spreading tree producing sour fruit pods indispensable in South Indian culinary tradition (Sambar, Rasam, Pulihora).",
        "native_region": "Tropical Africa & India",
        "growth_stage": "Perennial Timber & Pod Bearing",
        "growing_season": "Summer pod ripening (Jan - April)",
        "harvest_season": "Annual pod collection",
        "soil_type": "Deep alluvium or red gravelly soils with good drainage",
        "temperature_range": "18°C - 45°C",
        "water_requirement": "Extremely drought hardy after 3 years",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Organic manure and phosphate application prior to monsoon flushes",
        "economic_importance": "High-value culinary export commodity; hard red timber used for agricultural tools.",
        "common_uses": ["Culinary souring agent", "Tamarind seed powder industrial gum", "Heavy durable hardwood timber"],
        "common_diseases": ["Powdery Mildew of Tamarind", "Sooty Mold"],
        "common_pests": ["Fruit Borer", "Scale Insects"]
    },
    "coconut": {
        "common_name": "Coconut Palm / Kobbari Chettu",
        "regional_names": {
            "te": "కొబ్బరి చెట్టు (Kobbari Chettu)",
            "ta": "தென்னை மரம் (Thennaimaram)",
            "ml": "തെങ്ങ് (Thengu)",
            "kn": "ತೆಂಗಿನ ಮರ (Tengina Mara)",
            "mr": "नारळ (Naral)",
            "hi": "నారియల్ (Nariyal)"
        },
        "scientific_name": "Cocos nucifera",
        "family": "Arecaceae (Palm Family)",
        "category": "Multi-Purpose Plantation Palm Tree",
        "description": "The Kalpavriksha of coastal Andhra Pradesh, lining Konaseema, Godavari, and Srikakulam districts providing tender water, copra, and fiber.",
        "native_region": "Coastal Tropical Indo-Pacific",
        "growth_stage": "Continuous Frond & Bunch Production",
        "growing_season": "Year-round production",
        "harvest_season": "Every 45 - 60 days per mature palm",
        "soil_type": "Coastal sandy alluvium, red sandy loam with water table at 1.5-2m (pH 5.5 - 7.5)",
        "temperature_range": "24°C - 36°C with high ambient humidity",
        "water_requirement": "High: 40 - 50 liters per palm daily via drip or basin",
        "sunlight_requirement": "Full Sunlight (needs open sky)",
        "fertilizer_recommendation": "NPK 500:320:1200g per palm annually + 2kg Neem cake and Common Salt (NaCl)",
        "economic_importance": "Foundation of coastal Andhra rural economy: tender water, copra oil, coir fiber, and thatch.",
        "common_uses": ["Tender coconut water", "Copra oil extraction", "Culinary shredded coconut", "Coir rope & geotextiles"],
        "common_diseases": ["Bud Rot (Phytophthora)", "Basal Stem Rot / Thanjavur Wilt (Ganoderma)"],
        "common_pests": ["Rhinoceros Beetle", "Red Palm Weevil", "Eriophyid Mite"]
    },
    "teak": {
        "common_name": "Teak Tree / Teku Chettu",
        "regional_names": {
            "te": "టేకు చెట్టు (Teku Chettu)",
            "ta": "தேக்கு மரம் (Thekku)",
            "ml": "തേക്ക് (Thekku)",
            "kn": "ತೇಗದ ಮರ (Tegina Mara)",
            "mr": "सागवान (Sagwan)",
            "hi": "సాగావాన్ (Sagwan)"
        },
        "scientific_name": "Tectona grandis",
        "family": "Lamiaceae (Teak Family)",
        "category": "High-Value Commercial Timber Tree",
        "description": "Prized deciduous hardwood tree planted along Andhra farm boundaries and agro-forestry blocks for premium structural and furniture timber.",
        "native_region": "South and Southeast Asia",
        "growth_stage": "Long-term Wood Volume Increment (15-25 years)",
        "growing_season": "Rapid growth during monsoon",
        "harvest_season": "Harvest at 15 to 25 years rotation",
        "soil_type": "Deep moist well-drained alluvial and fertile red loam (pH 6.5 - 7.5)",
        "temperature_range": "18°C - 42°C",
        "water_requirement": "Moderate; requires distinct dry season for heartwood hardening",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Organic compost + NPK 100:50:50g per sapling during first 3 years",
        "economic_importance": "One of the most valuable timber crops in the world; termiticide oils prevent wood rot.",
        "common_uses": ["Shipbuilding and luxury furniture", "High-grade structural construction timber"],
        "common_diseases": ["Teak Leaf Rust (Olivea tectonae)", "Powdery Mildew"],
        "common_pests": ["Teak Defoliator (Hyblaea puera)", "Skeletonizer (Eutectona machaeralis)"]
    },
    "banyan": {
        "common_name": "Banyan Tree / Marri Chettu",
        "regional_names": {
            "te": "మర్రి చెట్టు (Marri Chettu)",
            "ta": "ஆலமரம் (Aalamaram)",
            "ml": "പേരാൽ (Peral)",
            "kn": "ಆಲದ ಮರ (Alada Mara)",
            "mr": "वड (Vad)",
            "hi": "బర్గాద్ / బడ్ (Bargad)"
        },
        "scientific_name": "Ficus benghalensis",
        "family": "Moraceae (Fig Family)",
        "category": "National & Sacred Shade Tree",
        "description": "Colossal evergreen tree with aerial prop roots that anchor into the ground, creating immense ecological canopies for village gathering and bird nesting.",
        "native_region": "Indian Subcontinent",
        "growth_stage": "Centuries-Old Massive Canopy Extension",
        "growing_season": "Year-round evergreen",
        "harvest_season": "Perennial ecological shelter",
        "soil_type": "Adaptable to all soils including rocky crevices",
        "temperature_range": "15°C - 45°C",
        "water_requirement": "Deep root system draws groundwater; highly drought hardy",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Natural leaf litter bio-cycling; zero chemical fertilizer needed",
        "economic_importance": "Keystone ecological species supporting hundreds of avian and insect species.",
        "common_uses": ["Vast cooling canopy shade", "Traditional latex and bark medicinal remedies"],
        "common_diseases": ["Ficus Leaf Blight"],
        "common_pests": ["Fig Wasps (Symbiotic)", "Scale Insects"]
    },
    "peepal": {
        "common_name": "Peepal Tree / Sacred Fig / Ravi Chettu",
        "regional_names": {
            "te": "రావి చెట్టు (Ravi Chettu)",
            "ta": "அரச மரம் (Arasamaram)",
            "ml": "അരയാൽ (Arayal)",
            "kn": "ಅರಳಿ ಮರ (Arali Mara)",
            "mr": "पिंपळ (Pimpal)",
            "hi": "పీపల్ (Peepal)"
        },
        "scientific_name": "Ficus religiosa",
        "family": "Moraceae (Fig Family)",
        "category": "Sacred Evergreen Shade Tree",
        "description": "Sacred large deciduous tree with heart-shaped leaves ending in an elegant drip tip that rustle even in the slightest breeze.",
        "native_region": "Indian Subcontinent",
        "growth_stage": "Massive Long-Lived Canopy Tree",
        "growing_season": "Year-round",
        "harvest_season": "N/A (Sacred tree)",
        "soil_type": "Deep well-drained loams, limestone crevices and rocky soils",
        "temperature_range": "15°C - 45°C",
        "water_requirement": "Low once rooted",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Self-sustaining natural organic decomposition",
        "economic_importance": "Produces high levels of oxygen day and night; central to rural cultural life.",
        "common_uses": ["Continuous oxygen emission & shade", "Ayurvedic bark decoction for wound healing"],
        "common_diseases": ["Ficus Rust"],
        "common_pests": ["Thrips", "Leaf Beetles"]
    },
    "jamun": {
        "common_name": "Jamun Tree / Neredu Chettu",
        "regional_names": {
            "te": "నేరేడు చెట్టు / అల్లనేరేడు (Neredu Chettu)",
            "ta": "நாவல் மரம் (Naavalmaram)",
            "ml": "ഞാവൽ (Njaval)",
            "kn": "ನೇರಳೆ ಮರ (Nerale Mara)",
            "mr": "जांभूळ (Jambhul)",
            "hi": "జామున్ (Jamun)"
        },
        "scientific_name": "Syzygium cumini",
        "family": "Myrtaceae (Myrtle Family)",
        "category": "Fruit, Timber & Health Tree",
        "description": "Large evergreen tree producing glossy purple-black berries celebrated for anti-diabetic medicinal qualities and deep farm boundary windbreaks.",
        "native_region": "Indian Subcontinent & Southeast Asia",
        "growth_stage": "Canopy Flush & Monsoon Fruiting",
        "growing_season": "Fruiting in early monsoon (June-July)",
        "harvest_season": "60 - 90 days from flower bloom",
        "soil_type": "Deep fertile moisture-retentive loamy and alluvial soils",
        "temperature_range": "18°C - 40°C",
        "water_requirement": "Moderate (Tolerates temporary flooding along streams)",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "FYM compost + NPK 500:250:500g per tree annually",
        "economic_importance": "High seasonal market demand for diabetic fruit; hard water-resistant timber used for well curbs.",
        "common_uses": ["Fresh fruit with anti-hyperglycemic properties", "Jamun seed powder for diabetes management", "Water-submerged structural timber"],
        "common_diseases": ["Leaf Spot", "Anthracnose"],
        "common_pests": ["Fruit Borer", "Whitefly"]
    },
    "sapota": {
        "common_name": "Sapota Tree / Chiku",
        "regional_names": {
            "te": "సపోటా చెట్టు (Sapota Chettu)",
            "ta": "சப்போட்டா மரம் (Sappotta)",
            "ml": "സപ്പോട്ട (Sappotta)",
            "kn": "ಚಿಕ್ಕು ಮರ (Chikku Mara)",
            "mr": "चिकू (Chiku)",
            "hi": "చీకూ (Chiku)"
        },
        "scientific_name": "Manilkara zapota",
        "family": "Sapotaceae (Sapodilla Family)",
        "category": "Perennial Fruit Orchard Tree",
        "description": "Hardy evergreen fruit tree with glossy dark leaves producing sweet malty brown fruits year-round, flourishing in Coastal Andhra coastal belt.",
        "native_region": "Central America & Mexico",
        "growth_stage": "Continuous Flowering & Fruiting",
        "growing_season": "Peak harvests in Oct-Nov and Feb-April",
        "harvest_season": "4 - 5 months from fruit set",
        "soil_type": "Deep sandy loam, alluvium or red laterite with good drainage (pH 6.0 - 8.0)",
        "temperature_range": "20°C - 38°C",
        "water_requirement": "Moderate drip irrigation (Drought tolerant)",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "NPK 1000:500:500g per mature tree annually in split doses",
        "economic_importance": "Reliable cash flow crop requiring far less pesticide spraying than other fruit orchards.",
        "common_uses": ["Fresh sweet table fruit", "Milkshakes and dried fruit flakes"],
        "common_diseases": ["Leaf Spot (Phaeophleospora)", "Sooty Mold"],
        "common_pests": ["Chiku Moth (Nephopteryx)", "Mealybugs"]
    },
    "drumstick": {
        "common_name": "Drumstick Tree / Munaga Chettu",
        "regional_names": {
            "te": "మునగ చెట్టు (Munaga Chettu)",
            "ta": "முருங்கை மரம் (Murungai)",
            "ml": "മുരിങ്ങ (Muringa)",
            "kn": "ನುಗ್ಗೆ ಮರ (Nugge Mara)",
            "mr": "शेवगा (Shevga)",
            "hi": "సహజన్ / మునగా (Sahjan)"
        },
        "scientific_name": "Moringa oleifera",
        "family": "Moringaceae (Horseradish Tree Family)",
        "category": "Nutritional Vegetable & Tree Crop",
        "description": "Fast-growing drought-hardy miracle tree yielding nutritious long green pods and vitamin-packed leaves essential to Andhra Sambar and curries.",
        "native_region": "Sub-Himalayan Indian Tracts",
        "growth_stage": "Rapid Vegetative Flush & Podding (6-8 months to first harvest)",
        "growing_season": "Year-round production with annual pruning",
        "harvest_season": "Pods harvested every 7 - 10 days",
        "soil_type": "Sandy loam or loamy soil with excellent drainage (Avoid waterlogging)",
        "temperature_range": "22°C - 40°C",
        "water_requirement": "Low to Moderate",
        "sunlight_requirement": "Full Sunlight",
        "fertilizer_recommendation": "Compost + NPK 100:100:50g per plant after each pruning flush",
        "economic_importance": "High-profit perennial vegetable; global demand for moringa leaf powder superfood.",
        "common_uses": ["Tender drumstick pods in Sambar and curries", "Nutritional moringa leaf stir-fry", "Seed oil purification"],
        "common_diseases": ["Pod Rot", "Cercospora Leaf Spot"],
        "common_pests": ["Moringa Hairy Caterpillar", "Bud Midge", "Aphids"]
    }
}

# Merge complete Andhra Pradesh regional trees, crops, fruits, vegetables, and weeds
try:
    from backend.app.services.plant_identifier.andhra_species import ANDHRA_SPECIES_DATABASE
except ImportError:
    try:
        from app.services.plant_identifier.andhra_species import ANDHRA_SPECIES_DATABASE
    except ImportError:
        from andhra_species import ANDHRA_SPECIES_DATABASE

PLANT_DATABASE.update(ANDHRA_SPECIES_DATABASE)

def get_plant_info(plant_key: str) -> dict:
    """
    Looks up plant information dictionary by key/name.
    Falls back to structured dynamic template if exact key isn't present.
    """
    normalized_key = plant_key.lower().strip()
    
    # Direct match check
    for key, data in PLANT_DATABASE.items():
        if key in normalized_key or normalized_key in key:
            return data.copy()

    # Dynamic fallback structured plant profile
    display_title = plant_key.replace('_', ' ').title()
    is_weed = any(w in normalized_key for w in ["weed", "grass", "gaddi", "pul", "gavat", "ghas", "parthenium", "cyperus"])
    
    cat = "Agricultural Weed" if is_weed else "Agricultural Crop"
    
    return {
        "common_name": f"{display_title} {'Weed' if is_weed else 'Crop'}",
        "regional_names": {
            "te": f"{display_title} (తెలుగు)",
            "ta": f"{display_title} (தமிழ்)",
            "ml": f"{display_title} (മലയാളം)",
            "kn": f"{display_title} (ಕನ್ನಡ)",
            "mr": f"{display_title} (मराठी)",
            "hi": f"{display_title} (हिंदी)"
        },
        "scientific_name": display_title,
        "family": cat,
        "category": cat,
        "description": f"Identified {cat.lower()} specimen ({display_title}).",
        "native_region": "South Indian Regional Agriculture",
        "growth_stage": "Active Growth",
        "growing_season": "Standard Regional Growing Season",
        "harvest_season": "N/A (Weed Control)" if is_weed else "60 - 90 days",
        "soil_type": "Fertile loamy farm soil (pH 6.0 - 7.0)",
        "temperature_range": "18°C - 38°C",
        "water_requirement": "Drought resilient" if is_weed else "Moderate Irrigation",
        "sunlight_requirement": "Full Sun",
        "fertilizer_recommendation": "Non-chemical hand weeding / mulching target" if is_weed else "Balanced NPK 10-10-10 with organic compost",
        "economic_importance": "Competes for soil nutrients; target for eradication." if is_weed else "Valuable food, spice, or forage crop.",
        "common_uses": ["Eradicate before seed formation to protect crop yields"] if is_weed else ["Crop production", "Culinary use", "Farming income"],
        "common_diseases": ["Weed Rust Fungus"] if is_weed else ["Foliar Spot", "Powdery Mildew", "Blight"],
        "common_pests": ["Biocontrol Weevils"] if is_weed else ["Aphids", "Borer Insects", "Mites"]
    }
