import os
import re
import json
import base64
import logging
from typing import Optional, Dict, Any
import httpx
from backend.app.core.config import settings

logger = logging.getLogger(__name__)

def safe_parse_json(text: str) -> Optional[dict]:
    """Extracts and parses JSON from markdown code fences or raw strings."""
    if not text:
        return None
    cleaned = text.strip()
    match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", cleaned, re.IGNORECASE)
    if match:
        cleaned = match.group(1).strip()
    try:
        return json.loads(cleaned)
    except Exception:
        brace_match = re.search(r"(\{[\s\S]*\})", cleaned)
        if brace_match:
            try:
                return json.loads(brace_match.group(1))
            except Exception:
                pass
    return None

EXTENSION_OFFICER_PROMPT = """You are an expert, local AI Agriculture Extension Officer and Plant Pathologist serving as the backend core for the AgriShield crop diagnostic platform. Your job is to analyze uploaded crop images, explicitly describe the visible plant anomalies, and return structured, clear results tailored for farmers using simple language.

When processing an image, you must strictly structure your response into these exact markdown blocks:

### 🚨 MAIN DIAGNOSIS HEADER
- **Host Plant/Crop**: [Identify the crop, e.g., Rice, Groundnut, Tomato]
- **Primary Diagnosis**: [Identify the most likely disease name or nutrient defect based on visual markers]
- **Confidence Rating**: [Provide a direct percentage, e.g., 92% Match]

### 🔍 VISUAL ANALYSIS BREAKDOWN
- **Observed Symptoms**: [Before providing a final conclusion, you MUST explicitly describe the specific visual features you observe on the leaf or plant structure in the image. Detail leaf lesions, spot colors, waxy secretions, margins, or wilting patterns in 2-3 simple sentences.]

### 🩹 DIFFERENTIAL DIAGNOSIS (Possibilities)
To ensure safety and scientific accuracy, you must provide exactly three distinct possibilities that share similar visual characteristics with this sample:
1. **[Possibility 1 Name]**: Shares visual traits such as [describe overlapping visual marker].
2. **[Possibility 2 Name]**: Shares visual traits such as [describe overlapping visual marker].
3. **[Possibility 3 Name]**: Shares visual traits such as [describe overlapping visual marker].

### 🌿 BIOLOGICAL ADVISORY (Eco-Friendly Control)
Provide exactly three distinct, natural field remedies:
1. **Field Cleanup**: [1 short, direct mechanical action like manual pruning or burning infected leaves]
2. **Water Management**: [1 short action modifying irrigation behavior to prevent pathogen spread]
3. **Organic Spray**: [1 specific natural formulation like homemade neem oil or dilute garlic spray]

### 🧪 PRO CHEMICAL ACTION PLAN (Market Control)
Provide exactly three distinct, safe chemical control strategies:
1. **Targeted Active Solution**: [Specify a standard, safe active ingredient class like Copper Oxychloride or Mancozeb]
2. **Alternative Compound**: [Provide a backup active ingredient class safe for this crop family]
3. **Prevention Routine**: [State the standard chemical application timeframe for protecting neighboring healthy crops]

⚠️ **Label Verification**: **Make sure to double-check the physical product label container to confirm that the product names, active concentrations, and biometric dosage values are completely accurate before execution in the field!**

Do not include conversational introductions or generic pleasantries. Output only the structured blocks."""

def parse_extension_officer_markdown(text: str) -> Dict[str, Any]:
    """
    Parses the exact 5 structured markdown blocks generated by the Extension Officer prompt.
    Returns normalized dictionary with parsed entities and the original raw markdown.
    """
    res = {
        "raw_markdown": text.strip() if text else "",
        "crop_name": "Agricultural Crop",
        "disease_name": "Crop Health Condition",
        "confidence": 0.92,
        "observed_symptoms": "",
        "differential_candidates": [],
        "biological_advisory": {
            "field_cleanup": "Prune and safely burn or bury severely infected lower foliage to reduce local inoculum.",
            "water_management": "Avoid overhead sprinkler irrigation; switch to drip watering to keep foliage dry.",
            "organic_spray": "Spray cold-pressed neem oil (10,000 ppm) @ 5 ml/L with mild surfactant or Trichoderma viride @ 5 g/L."
        },
        "pro_chemical_plan": {
            "targeted_solution": "Apply standard protectant fungicide (Mancozeb 75% WP or Copper Oxychloride 50% WP @ 2.5 g/L).",
            "alternative_compound": "Systemic alternative (Azoxystrobin 18.2% + Difenoconazole 11.4% SC @ 1 ml/L or Hexaconazole 5% EC @ 2 ml/L).",
            "prevention_routine": "Spray neighboring healthy border plants within 48 hours to create a protective chemical buffer."
        },
        "label_verification": "Make sure to double-check the physical product label container to confirm that the product names, active concentrations, and biometric dosage values are completely accurate before execution in the field!"
    }
    if not text:
        return res

    # 1. Host Plant / Crop
    crop_m = re.search(r"-\s*\*\*Host Plant/Crop\*\*:\s*([^\n\r]+)", text, re.IGNORECASE)
    if crop_m:
        res["crop_name"] = crop_m.group(1).strip().strip("[]").title()

    # 2. Primary Diagnosis
    diag_m = re.search(r"-\s*\*\*Primary Diagnosis\*\*:\s*([^\n\r]+)", text, re.IGNORECASE)
    if diag_m:
        res["disease_name"] = diag_m.group(1).strip().strip("[]").title()

    # 3. Confidence Rating
    conf_m = re.search(r"-\s*\*\*Confidence Rating\*\*:\s*([^\n\r]+)", text, re.IGNORECASE)
    if conf_m:
        c_str = conf_m.group(1).strip()
        num_m = re.search(r"(\d+(?:\.\d+)?)", c_str)
        if num_m:
            raw_pct = float(num_m.group(1))
            res["confidence"] = raw_pct / 100.0 if raw_pct > 1.0 else raw_pct

    # 4. Observed Symptoms
    sym_m = re.search(r"-\s*\*\*Observed Symptoms\*\*:\s*([^\n\r]+(?:\n(?!\s*###|\s*-|\s*\d+\.).*)*)", text, re.IGNORECASE)
    if sym_m:
        clean_sym = re.sub(r"\s+", " ", sym_m.group(1).strip()).strip("[]")
        res["observed_symptoms"] = clean_sym

    # 5. Differential Candidates (extract up to 3)
    diff_block_m = re.search(r"###\s*🩹\s*DIFFERENTIAL DIAGNOSIS[\s\S]*?(?=###|\Z)", text, re.IGNORECASE)
    if diff_block_m:
        diff_text = diff_block_m.group(0)
        items = re.findall(r"\d+\.\s*\*\*([^*]+)\*\*:\s*([^\n\r]+)", diff_text)
        candidates = []
        for idx, (cand_name, trait_desc) in enumerate(items[:3]):
            clean_name = cand_name.strip().strip("[]")
            clean_trait = trait_desc.strip().strip("[]")
            cand_conf = max(0.20, (res["confidence"] if idx == 0 else (res["confidence"] * (0.85 - idx * 0.12))))
            candidates.append({
                "disease_name": clean_name,
                "crop_name": res["crop_name"],
                "confidence": round(cand_conf * 100, 1),
                "visual_hallmark": clean_trait
            })
        if candidates:
            res["differential_candidates"] = candidates

    # 6. Biological Advisory
    bio_block_m = re.search(r"###\s*🌿\s*BIOLOGICAL ADVISORY[\s\S]*?(?=###|\Z)", text, re.IGNORECASE)
    if bio_block_m:
        bio_text = bio_block_m.group(0)
        cu_m = re.search(r"\d+\.\s*\*\*Field Cleanup\*\*:\s*([^\n\r]+)", bio_text, re.IGNORECASE)
        wm_m = re.search(r"\d+\.\s*\*\*Water Management\*\*:\s*([^\n\r]+)", bio_text, re.IGNORECASE)
        os_m = re.search(r"\d+\.\s*\*\*Organic Spray\*\*:\s*([^\n\r]+)", bio_text, re.IGNORECASE)
        if cu_m:
            res["biological_advisory"]["field_cleanup"] = cu_m.group(1).strip().strip("[]")
        if wm_m:
            res["biological_advisory"]["water_management"] = wm_m.group(1).strip().strip("[]")
        if os_m:
            res["biological_advisory"]["organic_spray"] = os_m.group(1).strip().strip("[]")

    # 7. Pro Chemical Action Plan
    chem_block_m = re.search(r"###\s*🧪\s*PRO CHEMICAL ACTION PLAN[\s\S]*?(?=⚠️|\Z)", text, re.IGNORECASE)
    if chem_block_m:
        chem_text = chem_block_m.group(0)
        ta_m = re.search(r"\d+\.\s*\*\*Targeted Active Solution\*\*:\s*([^\n\r]+)", chem_text, re.IGNORECASE)
        ac_m = re.search(r"\d+\.\s*\*\*Alternative Compound\*\*:\s*([^\n\r]+)", chem_text, re.IGNORECASE)
        pr_m = re.search(r"\d+\.\s*\*\*Prevention Routine\*\*:\s*([^\n\r]+)", chem_text, re.IGNORECASE)
        if ta_m:
            res["pro_chemical_plan"]["targeted_solution"] = ta_m.group(1).strip().strip("[]")
        if ac_m:
            res["pro_chemical_plan"]["alternative_compound"] = ac_m.group(1).strip().strip("[]")
        if pr_m:
            res["pro_chemical_plan"]["prevention_routine"] = pr_m.group(1).strip().strip("[]")

    return res

def generate_fallback_extension_officer_report(crop: str, disease: str, confidence: float) -> Dict[str, Any]:
    """Generates agronomy-grade 5 structured blocks deterministically if Gemini is offline."""
    c_title = (crop or "Agricultural Crop").strip().title()
    d_title = (disease or "Crop Health Condition").strip().title()
    conf_pct = f"{min(99.4, max(75.0, confidence * 100 if confidence <= 1.0 else confidence)):.1f}%"
    conf_num = float(conf_pct.replace("%", "")) / 100.0

    # Deterministic candidates by crop
    c_low = c_title.lower()
    d_low = d_title.lower()

    if "rice" in c_low or "paddy" in c_low:
        cand2_name = "Brown Spot" if "blast" in d_low else "Leaf Blast"
        cand2_trait = "Overlapping circular to oval lesions across foliar leaf blade."
        cand3_name = "Sheath Blight"
        cand3_trait = "Water-soaked irregular snake-skin lesions near lower waterline stems."
    elif "cotton" in c_low:
        cand2_name = "Bacterial Blight (Angular Leaf Spot)"
        cand2_trait = "Angular dark lesions restricted by leaf vein architecture."
        cand3_name = "Alternaria Leaf Spot"
        cand3_trait = "Concentric brown zonate markings with chlorotic yellow boundaries."
    elif "tomato" in c_low or "potato" in c_low:
        cand2_name = "Late Blight" if "early" in d_low else "Early Blight"
        cand2_trait = "Rapidly expanding dark brown to black foliar lesions with chlorotic halos."
        cand3_name = "Septoria Leaf Spot"
        cand3_trait = "Numerous small circular spots with darker outer borders and necrotic centers."
    elif "chilli" in c_low or "pepper" in c_low:
        cand2_name = "Anthracnose (Dieback)"
        cand2_trait = "Sunken circular dark spots with visible concentric acervuli rings."
        cand3_name = "Bacterial Leaf Spot"
        cand3_trait = "Small water-soaked angular lesions turning brownish-black on leaves."
    elif "groundnut" in c_low or "peanut" in c_low:
        cand2_name = "Late Leaf Spot (Phaeoisariopsis)"
        cand2_trait = "Dark carbonaceous spots primarily on lower foliar surface."
        cand3_name = "Rust (Puccinia)"
        cand3_trait = "Brownish-orange pustules rupturing foliar epidermis on leaf undersides."
    else:
        cand2_name = "Alternaria Leaf Spot"
        cand2_trait = "Zonate concentric lesions with prominent chlorotic margins."
        cand3_name = "Anthracnose"
        cand3_trait = "Sunken necrotic lesions with dark sporulating center rings."

    cand1_trait = f"Primary visual markers consistent with {d_title} lesions and chlorosis on {c_title}."

    raw_md = f"""### 🚨 MAIN DIAGNOSIS HEADER
- **Host Plant/Crop**: {c_title}
- **Primary Diagnosis**: {d_title}
- **Confidence Rating**: {conf_pct} Match

### 🔍 VISUAL ANALYSIS BREAKDOWN
- **Observed Symptoms**: Distinct foliar lesions with chlorotic yellow margins and focal necrotic patches observed on the leaf surface. Foliar tissue exhibits early cellular necrosis along lateral margins with localized loss of photosynthetic green pigment.

### 🩹 DIFFERENTIAL DIAGNOSIS (Possibilities)
To ensure safety and scientific accuracy, you must provide exactly three distinct possibilities that share similar visual characteristics with this sample:
1. **{d_title}**: Shares visual traits such as {cand1_trait}
2. **{cand2_name}**: Shares visual traits such as {cand2_trait}
3. **{cand3_name}**: Shares visual traits such as {cand3_trait}

### 🌿 BIOLOGICAL ADVISORY (Eco-Friendly Control)
Provide exactly three distinct, natural field remedies:
1. **Field Cleanup**: Manually clip and collect heavily spotted lower leaves; burn or deeply bury residues away from cultivated plots.
2. **Water Management**: Switch from overhead wetting to ground/drip irrigation; water early in the morning so morning dew evaporates rapidly.
3. **Organic Spray**: Spray cold-pressed Neem Seed Kernel Extract (NSKE 5%) or Neem Oil (10,000 ppm) @ 5 ml/L water with 1 ml soap emulsifier.

### 🧪 PRO CHEMICAL ACTION PLAN (Market Control)
Provide exactly three distinct, safe chemical control strategies:
1. **Targeted Active Solution**: Spray Mancozeb 75% WP @ 2.5 g/L (50g/20L tank) or Copper Oxychloride 50% WP @ 3.0 g/L for contact protection.
2. **Alternative Compound**: Rotate with systemic Azoxystrobin 18.2% + Difenoconazole 11.4% SC @ 1.0 ml/L or Hexaconazole 5% EC @ 2.0 ml/L.
3. **Prevention Routine**: Spray healthy perimeter rows within a 15-meter buffer radius within 48 hours to prevent airborne spore dissemination.

⚠️ **Label Verification**: **Make sure to double-check the physical product label container to confirm that the product names, active concentrations, and biometric dosage values are completely accurate before execution in the field!**"""

    return parse_extension_officer_markdown(raw_md)

async def cross_verify_disease_with_vision(
    image_path: str,
    crop_hint: Optional[str] = None
) -> Optional[Dict[str, Any]]:
    """
    Expert multimodal diagnosis using the official Agricultural Extension Officer & Plant Pathologist prompt.
    Analyzes visible plant anomalies and parses the 5 structured markdown blocks.
    """
    gemini_key = getattr(settings, "GEMINI_API_KEY", "")
    if not gemini_key or "mock" in gemini_key or "PASTE" in gemini_key:
        logger.debug("Gemini API key not configured for Extension Officer vision.")
        return None

    if not os.path.exists(image_path):
        logger.warning(f"Image path for Gemini vision does not exist: {image_path}")
        return None

    try:
        with open(image_path, "rb") as f:
            image_bytes = f.read()
        b64_img = base64.b64encode(image_bytes).decode("utf-8")

        prompt = EXTENSION_OFFICER_PROMPT
        if crop_hint:
            prompt += f"\n\nContext Hint: The farmer indicates this plant is {crop_hint}."

        payload = {
            "contents": [{
                "parts": [
                    {"text": prompt},
                    {"inline_data": {"mime_type": "image/jpeg", "data": b64_img}}
                ]
            }],
            "generationConfig": {
                "temperature": 0.1,
                "maxOutputTokens": 1024
            }
        }

        models_to_try = ["gemini-flash-lite-latest", "gemini-flash-latest"]
        async with httpx.AsyncClient(timeout=14.0) as client:
            for model_name in models_to_try:
                try:
                    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent?key={gemini_key}"
                    resp = await client.post(url, json=payload)
                    if resp.status_code == 200:
                        data = resp.json()
                        candidates = data.get("candidates", [])
                        if candidates:
                            parts = candidates[0].get("content", {}).get("parts", [])
                            if parts:
                                raw_text = "".join([p.get("text", "") for p in parts]).strip()
                                parsed = parse_extension_officer_markdown(raw_text)
                                if parsed and parsed.get("disease_name") and parsed["disease_name"] != "Crop Health Condition":
                                    logger.info(f"Gemini Extension Officer diagnosis succeeded with model {model_name}")
                                    return parsed
                except Exception as m_err:
                    logger.debug(f"Gemini model {model_name} extension officer attempt: {m_err}")
                    continue

    except Exception as e:
        logger.warning(f"Gemini Extension Officer vision diagnosis failed: {e}")

    return None

async def extract_agrochemical_label_vision(image_path: str) -> Optional[Dict[str, Any]]:
    """
    Reads commercial agrochemical bottle, packet, sack, or canister labels directly using Gemini Vision.
    Extracts brand, manufacturer, active ingredients, category (Fertilizer/Insecticide/Fungicide/Herbicide/PGR/Bio-Pesticide),
    detailed description, target crops, fertilizer growth stages, 4 mixing steps, and PPE guidelines.
    """
    gemini_key = getattr(settings, "GEMINI_API_KEY", "")
    if not gemini_key or "mock" in gemini_key or "PASTE" in gemini_key:
        return None

    if not os.path.exists(image_path):
        return None

    try:
        with open(image_path, "rb") as f:
            image_bytes = f.read()
        b64_img = base64.b64encode(image_bytes).decode("utf-8")

        prompt = """You are an expert agricultural scientist, chemist, and agrochemical packaging inspector.
Analyze this photo of an agricultural chemical container, bottle, carton, sachet, or fertilizer bag.
Read all visible text, logos, formulations, and Indian regional scripts (Hindi, Telugu, Tamil, Marathi, English).

Accurately classify the product into one of the following exact categories:
- 'Fertilizer' (e.g., Urea, DAP 18-46-0, MOP 0-0-60, NPK complexes, Nano Urea, Nano DAP, Chelated Micronutrients, Zinc, Boron)
- 'Insecticide' (e.g., Coragen, Actara, Confidor, Admire, Regent, Tracer, Chlorpyrifos, Profenofos, Monocrotophos)
- 'Fungicide' (e.g., SAAF, Bavistin, Indofil M-45, Blitox 50, Contaf Plus, Tilt, Score, Nativo, Amistar Top, Ridomil Gold)
- 'Herbicide' (e.g., Roundup / Glyphosate, Gramoxone / Paraquat, Stomp / Pendimethalin, Nominee Gold, 2,4-D, Rifit)
- 'Plant Growth Regulator' (e.g., Gibberellic Acid GA3, Cultar / Paclobutrazol, Planofix NAA, Lihocin)
- 'Bio-Pesticide' (e.g., Neem Oil, Azadirachtin, Trichoderma, Pseudomonas)

Extract and return ONLY a valid JSON object matching this structure:
{
  "brand_name": "<Commercial Brand Name & numeric ratio on the package, e.g. Bharat NPK 19:19:19, Coragen, SAAF, Amistar Top>",
  "manufacturer": "<Company / Manufacturer name & location if visible, e.g. Bharat Rasayan / PMBJP New Delhi, FMC, UPL, Syngenta>",
  "active_ingredients": "<Active ingredients, NPK percentages, or chemical active compounds, e.g. Total Nitrogen 19% + Available Phosphate 19% + Potash 19%>",
  "product_type": "<Fertilizer / Insecticide / Fungicide / Herbicide / Plant Growth Regulator / Bio-Pesticide>",
  "primary_function": "<Short 1-sentence explanation of what it does for crops, e.g. Provides balanced macronutrients for vegetative vigor, root expansion, and fruit formation>",
  "detailed_description": "<A medium 5 to 10 sentence overview of what this product is, its primary agricultural purpose, and the target crops it benefits based on its composition>",
  "target_crops": ["<Crop 1>", "<Crop 2>", "<Crop 3>"],
  "target_diseases_and_pests": ["<Target pest, disease, or deficiency 1>", "<Target pest, disease, or deficiency 2>"],
  "dilution_rate_per_litre": "<Exact dilution per 1 Litre of clean water only, e.g. 5.0 g / L or 2.0 mL / L. Do NOT write per acre or 20L pump>",
  "spray_interval": "<Repeat spray frequency, e.g. Repeat after 10 to 14 days if disease or pest pressure continues, or at critical growth stages for fertilizer>",
  "preharvest_interval_days": 14,
  "fertilizer_growth_stages": {
    "vegetative": "<How it helps in vegetative stage, e.g. rapid root expansion, vigorous tillering, and healthy foliage growth>",
    "flowering": "<How it helps in flowering stage, e.g. prevents flower drop, stimulates bud initiation, and enhances pollination>",
    "fruiting_grain": "<How it helps in fruiting/grain filling stage, e.g. accelerates fruit sizing, uniform color, brix sweetness, and grain weight>"
  },
  "step_by_step_mixing": [
    "Measure the exact chemical dose needed using a clean measuring scoop or cup.",
    "Pre-dilute by stirring thoroughly into 2 to 3 litres of clean water in a plastic mixing bucket to form a uniform primary slurry.",
    "Pour the pre-mixed suspension into the spray tank filled halfway with clean water through the inlet filter strainer.",
    "Fill the remaining water to the calibrated mark, agitate gently, and spray uniformly over both upper and lower leaf surfaces."
  ],
  "ppe_guidelines": [
    "Wear chemical-resistant rubber/nitrile gloves when handling and mixing concentrate.",
    "Wear protective safety goggles or transparent shield to protect eyes from accidental splashes.",
    "Wear an N95 particulate / vapor respirator mask while spraying to avoid inhaling fine chemical mist.",
    "Wear full-sleeve protective clothing and rubber boots during application.",
    "Wash hands, face, and spray equipment thoroughly with clean water and soap immediately after spraying."
  ],
  "toxicity_hazard": "<Green (Caution) / Blue (Warning) / Yellow (Danger) / Red (Poison)>",
  "mrp_price": "<Retail Price (MRP) with currency symbol, e.g. ₹1,470 or Not visible on label>",
  "government_subsidy": "<Government subsidy amount if visible or applicable, e.g. Subsidized under PMBJP / ₹2,200 per bag>",
  "net_weight": "<Net Weight or volume, e.g. 50 kg, 45 kg, 1 Litre, 500 g>",
  "extracted_text_summary": "<Key visible words, numbers, and text extracted from the label>"
}
Do NOT output any markdown blocks or conversational text outside the JSON object."""

        payload = {
            "contents": [{
                "parts": [
                    {"text": prompt},
                    {"inline_data": {"mime_type": "image/jpeg", "data": b64_img}}
                ]
            }],
            "generationConfig": {
                "temperature": 0.1,
                "maxOutputTokens": 2048
            }
        }

        models_to_try = [
            "gemini-flash-lite-latest",
            "gemini-flash-latest"
        ]
        async with httpx.AsyncClient(timeout=12.0) as client:
            for model_name in models_to_try:
                try:
                    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent?key={gemini_key}"
                    resp = await client.post(url, json=payload)
                    if resp.status_code == 200:
                        data = resp.json()
                        candidates = data.get("candidates", [])
                        if candidates:
                            parts = candidates[0].get("content", {}).get("parts", [])
                            if parts:
                                text = "".join([p.get("text", "") for p in parts]).strip()
                                parsed = safe_parse_json(text)
                                if parsed and isinstance(parsed, dict) and parsed.get("brand_name"):
                                    logger.info(f"Gemini Vision agrochemical OCR succeeded with model {model_name}")
                                    return parsed
                except Exception as m_err:
                    logger.debug(f"Gemini model {model_name} agrochemical vision attempt: {m_err}")
                    continue

    except Exception as e:
        logger.warning(f"Gemini Vision agrochemical label OCR failed: {e}")

    return None
