/**
 * Utilities for 1-Click WhatsApp Sharing and 1-Page Printable Prescription Slips
 */

/**
 * Generates formatted WhatsApp diagnostic text and opens WhatsApp share URL
 */
export const shareDiagnosticToWhatsApp = ({
  cropName = 'Crop',
  diseaseName = 'Foliar Infection',
  confidence = 98,
  severity = 'Moderate',
  chemicals = [],
  organic = [],
  prevention = '',
  acres = 1.0,
  farmLocation = 'Field Sector',
  farmerName = 'Farmer'
}) => {
  const dateStr = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const waterLiters = Math.round(acres * 150);
  const tankPumps = Math.ceil(waterLiters / 15);

  const cleanChemicals = Array.isArray(chemicals) && chemicals.length > 0 
    ? chemicals.map(c => `  💊 ${c}`).join('\n')
    : '  💊 Consult local agronomy officer for registered chemical spray.';

  const cleanOrganic = Array.isArray(organic) && organic.length > 0
    ? organic.map(o => `  🌿 ${o}`).join('\n')
    : '  🌿 Neem oil (5ml/L) or Trichoderma viride foliar wash.';

  const message = 
`🌾 *AGRISHIELD AI — CROP HEALTH REPORT* 🌾
━━━━━━━━━━━━━━━━━━━━
👨‍🌾 *Farmer:* ${farmerName}
📍 *Location:* ${farmLocation}
📅 *Date:* ${dateStr}

🌱 *Crop:* ${cropName}
🚨 *Diagnosis:* ${diseaseName}
🎯 *AI Accuracy:* ${confidence}%
⚠️ *Severity Level:* ${severity}

💊 *RECOMMENDED MEDICINE & DOSAGES:*
${cleanChemicals}

🌿 *ORGANIC / BIOLOGICAL REMEDIES:*
${cleanOrganic}

🚜 *FIELD SPRAY REQUIREMENT (${acres} Acres):*
  • Water Volume: ~${waterLiters} Liters
  • Spray Tanks: ~${tankPumps} Knapsack Pumps (15L each)

🛡️ *PREVENTION:*
${prevention || 'Maintain clean irrigation, weed borders, and crop rotation.'}

━━━━━━━━━━━━━━━━━━━━
Generated by *AgriShield AI Precision Farming Platform*
Verified with NVIDIA NIM & PyTorch Vision Engine`;

  const url = `https://api.whatsapp.com/send?text=${encodeURIComponent(message)}`;
  window.open(url, '_blank');
};

/**
 * Generates and triggers a 1-page printable clinical Prescription Slip
 */
export const printPrescriptionSlip = ({
  cropName = 'Crop',
  diseaseName = 'Foliar Infection',
  confidence = 98,
  severity = 'Moderate',
  chemicals = [],
  organic = [],
  prevention = '',
  acres = 1.0,
  farmLocation = 'Pasupugallu',
  farmerName = 'Farmer',
  doctorNote = 'Early foliar spray recommended before dewfall.'
}) => {
  const dateStr = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const waterLiters = Math.round(acres * 150);
  const tankPumps = Math.ceil(waterLiters / 15);
  const rxId = 'AGRI-RX-' + Math.floor(100000 + Math.random() * 900000);

  const printWindow = window.open('', '_blank', 'width=850,height=1100');
  if (!printWindow) {
    alert('Please allow pop-ups in your browser to download the Prescription PDF.');
    return;
  }

  const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>AgriShield AI Prescription - ${rxId}</title>
  <style>
    @page { size: A4 portrait; margin: 15mm; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #1a202c;
      margin: 0;
      padding: 24px;
      line-height: 1.4;
      background: #fff;
    }
    .header {
      border-bottom: 3px solid #059669;
      padding-bottom: 12px;
      margin-bottom: 16px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .brand {
      font-size: 24px;
      font-weight: 900;
      color: #065f46;
      letter-spacing: -0.5px;
    }
    .brand span { color: #10b981; }
    .sub-brand {
      font-size: 11px;
      font-weight: bold;
      color: #6b7280;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    .meta-box {
      text-align: right;
      font-size: 11px;
      color: #4b5563;
    }
    .meta-box strong { color: #111827; }
    
    .patient-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 10px;
      background: #f0fdf4;
      border: 1px solid #bbf7d0;
      border-radius: 12px;
      padding: 12px 16px;
      margin-bottom: 18px;
    }
    .grid-cell { font-size: 12px; }
    .grid-label { font-size: 10px; font-weight: bold; color: #047857; text-transform: uppercase; }
    .grid-val { font-weight: 800; color: #0f172a; margin-top: 2px; }

    .rx-title {
      font-size: 18px;
      font-weight: 900;
      color: #065f46;
      display: flex;
      align-items: center;
      gap: 8px;
      margin-bottom: 10px;
      border-bottom: 1px solid #e5e7eb;
      padding-bottom: 6px;
    }
    .rx-badge {
      font-size: 11px;
      background: #fee2e2;
      color: #b91c1c;
      padding: 2px 8px;
      border-radius: 999px;
      font-weight: bold;
    }
    
    table.med-table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 16px;
      font-size: 12px;
    }
    table.med-table th {
      background: #047857;
      color: white;
      text-align: left;
      padding: 8px 10px;
      font-size: 11px;
      text-transform: uppercase;
    }
    table.med-table td {
      border-bottom: 1px solid #e5e7eb;
      padding: 8px 10px;
      color: #374151;
    }
    table.med-table tr:nth-child(even) { background: #f9fafb; }

    .spray-box {
      background: #eff6ff;
      border: 1px dashed #60a5fa;
      border-radius: 10px;
      padding: 12px 14px;
      margin-bottom: 16px;
      font-size: 11px;
    }
    .spray-box h4 {
      margin: 0 0 6px 0;
      color: #1d4ed8;
      font-size: 12px;
      font-weight: bold;
    }

    .organic-box {
      background: #fafaf9;
      border: 1px solid #e7e5e4;
      border-radius: 10px;
      padding: 10px 14px;
      margin-bottom: 16px;
      font-size: 11px;
    }
    .organic-box h4 {
      margin: 0 0 4px 0;
      color: #44403c;
      font-size: 11px;
      text-transform: uppercase;
    }

    .footer {
      border-top: 2px solid #e5e7eb;
      padding-top: 14px;
      margin-top: 24px;
      display: flex;
      justify-content: space-between;
      align-items: flex-end;
      font-size: 10px;
      color: #6b7280;
    }
    .stamp-box {
      text-align: center;
      border: 2px dashed #059669;
      border-radius: 8px;
      padding: 6px 14px;
      color: #059669;
      font-weight: 800;
      font-size: 10px;
      line-height: 1.3;
    }
  </style>
</head>
<body>

  <div class="header">
    <div>
      <div class="brand">AgriShield <span>AI</span></div>
      <div class="sub-brand">Autonomous Crop Clinic & Smart Pathology Sentinel</div>
    </div>
    <div class="meta-box">
      <div><strong>Prescription ID:</strong> ${rxId}</div>
      <div><strong>Date:</strong> ${dateStr}</div>
      <div><strong>Status:</strong> CLINIC VERIFIED</div>
    </div>
  </div>

  <div class="patient-grid">
    <div class="grid-cell">
      <div class="grid-label">Farmer Name</div>
      <div class="grid-val">${farmerName}</div>
    </div>
    <div class="grid-cell">
      <div class="grid-label">Farm Location</div>
      <div class="grid-val">${farmLocation}</div>
    </div>
    <div class="grid-cell">
      <div class="grid-label">Diagnosed Crop</div>
      <div class="grid-val">${cropName}</div>
    </div>
    <div class="grid-cell">
      <div class="grid-label">Field Area</div>
      <div class="grid-val">${acres} Acres</div>
    </div>
  </div>

  <div class="rx-title">
    <span>℞ Pathology Diagnosis: ${diseaseName}</span>
    <span class="rx-badge">Accuracy: ${confidence}%</span>
  </div>

  <table class="med-table">
    <thead>
      <tr>
        <th style="width: 35%;">Prescribed Agrochemical</th>
        <th style="width: 25%;">Recommended Dosage</th>
        <th style="width: 25%;">Spray Schedule</th>
        <th style="width: 15%;">Pre-Harvest (PHI)</th>
      </tr>
    </thead>
    <tbody>
      ${chemicals.map(c => `
        <tr>
          <td><strong>${c.split('@')[0] || c}</strong></td>
          <td>${c.split('@')[1] ? c.split('@')[1].split('(')[0] : 'As per label'}</td>
          <td>Every 7–10 days</td>
          <td>14 Days</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="spray-box">
    <h4>🚜 Calibrated Spray Requirement for ${acres} Acres:</h4>
    <div>• <strong>Required Foliar Water Volume:</strong> ~${waterLiters} Liters (${acres} acres × 150 L/acre)</div>
    <div>• <strong>Knapsack Sprayer Pumps:</strong> ~${tankPumps} full tanks (15 Liters capacity per knapsack pump)</div>
    <div>• <strong>Optimal Spray Conditions:</strong> Early morning before 9:00 AM or late afternoon after 4:00 PM. Avoid spraying if rain is forecast within 4 hours.</div>
  </div>

  <div class="organic-box">
    <h4>🌱 Biological & Organic Alternatives:</h4>
    <div>${organic.join(' • ') || 'Neem oil spray (5ml/L) + Trichoderma viride biological wash.'}</div>
    <div style="margin-top: 4px;">• <strong>Cultural Practice:</strong> ${prevention || 'Practice clean crop rotation and discard infected foliage.'}</div>
  </div>

  <div class="footer">
    <div>
      <div><strong>AgriShield Precision AI Vision Engine</strong></div>
      <div>Powered by PyTorch EfficientNetV2 + NVIDIA NIM Pathology Microservices</div>
      <div>Government APMC & Mandi Standards Compliant</div>
    </div>
    <div class="stamp-box">
      <div>✓ AGRISHIELD CLINICAL LAB</div>
      <div>AUTONOMOUS TELE-DIAGNOSTIC</div>
    </div>
  </div>

  <script>
    window.onload = function() {
      window.print();
    };
  </script>
</body>
</html>
  `;

  printWindow.document.open();
  printWindow.document.write(htmlContent);
  printWindow.document.close();
};
