/**
 * Multilingual Utilities for 1-Click WhatsApp Sharing and 1-Page Printable Prescription Slips
 * Supports English, Telugu (తెలుగు), Hindi (हिन्दी), Tamil (தமிழ்), and Kannada (ಕನ್ನಡ)
 */

export const RX_TRANSLATIONS = {
  en: {
    reportTitle: "AGRISHIELD AI — CROP HEALTH REPORT",
    farmer: "Farmer",
    location: "Location",
    date: "Date",
    crop: "Crop",
    diagnosis: "Diagnosis",
    confidence: "AI Accuracy",
    severity: "Severity Level",
    medicines: "RECOMMENDED MEDICINE & DOSAGES",
    organic: "ORGANIC / BIOLOGICAL REMEDIES",
    fieldReq: "FIELD SPRAY REQUIREMENT",
    waterVolume: "Required Water Volume",
    sprayTanks: "Spray Tanks",
    knapsackNote: "Knapsack Pumps (15L each)",
    prevention: "PREVENTION",
    rxId: "Prescription ID",
    clinicVerified: "CLINIC VERIFIED",
    prescribedChemical: "Prescribed Agrochemical",
    dosage: "Recommended Dosage",
    spraySchedule: "Spray Schedule",
    phi: "Pre-Harvest (PHI)",
    sprayConditions: "Early morning before 9:00 AM or late afternoon after 4:00 PM. Avoid spraying if rain is forecast within 4 hours.",
    bioHeader: "Biological & Organic Alternatives",
    culturalPractice: "Cultural Practice",
    fieldArea: "Field Area",
    footerTitle: "AgriShield Precision AI Vision Engine",
    footerSub: "Powered by PyTorch EfficientNetV2 + NVIDIA NIM Pathology Microservices",
    footerGov: "Government APMC & Mandi Standards Compliant",
    stampLab: "AGRISHIELD CLINICAL LAB",
    stampType: "AUTONOMOUS TELE-DIAGNOSTIC",
    footerCredit: "Generated by AgriShield AI Precision Farming Platform"
  },
  te: {
    reportTitle: "అగ్రిషీల్డ్ AI — పంట ఆరోగ్య నివేదిక",
    farmer: "రైతు పేరు",
    location: "గ్రామం / ప్రాంతం",
    date: "తేదీ",
    crop: "పంట",
    diagnosis: "వ్యాధి నిర్ధారణ",
    confidence: "AI ఖచ్చితత్వం",
    severity: "తీవ్రత స్థాయి",
    medicines: "సిఫార్సు చేసిన మందులు & మోతాదు",
    organic: "సేంద్రీయ & జీవ నియంత్రణ చర్యలు",
    fieldReq: "చేను స్ప్రే అవసరాలు",
    waterVolume: "అవసరమైన నీటి పరిమాణం",
    sprayTanks: "స్ప్రే పంపులు",
    knapsackNote: "న్యాప్‌సాక్ పంపులు (15 లీటర్లు ప్రతి పంపు)",
    prevention: "ముందస్తు నివారణ చర్యలు",
    rxId: "ప్రిస్క్రిప్షన్ ఐడి",
    clinicVerified: "క్లినిక్ ధృవీకరించబడింది",
    prescribedChemical: "సిఫార్సు చేసిన పురుగు / శిలీంద్ర నాశిని",
    dosage: "సిఫార్సు మోతాదు",
    spraySchedule: "స్ప్రే విరామం",
    phi: "కోతకు ముందు సమయం (PHI)",
    sprayConditions: "ఉదయం 9:00 గంటల లోపు లేదా సాయంత్రం 4:00 గంటల తర్వాత పిచికారీ చేయాలి. రాబోయే 4 గంటల్లో వర్షం కురిసే అవకాశం ఉంటే పిచికారీ చేయవద్దు.",
    bioHeader: "సేంద్రీయ & బయో ప్రత్యామ్నాయాలు",
    culturalPractice: "వ్యవసాయ పద్ధతి",
    fieldArea: "పొలం విస్తీర్ణం",
    footerTitle: "అగ్రిషీల్డ్ ప్రెసిషన్ AI విజన్ ఇంజిన్",
    footerSub: "పైటార్చ్ ఎఫీషియెంట్-నెట్ మరియు ఎన్విడియా నిమ్ సహాయంతో",
    footerGov: "ప్రభుత్వ మార్కెటింగ్ మరియు వ్యవసాయ ప్రమాణాలకు అనుగుణంగా",
    stampLab: "అగ్రిషీల్డ్ క్లినికల్ ల్యాబ్",
    stampType: "డిజిటల్ పంట వైద్య సేవ",
    footerCredit: "అగ్రిషీల్డ్ AI స్మార్ట్ ఫార్మింగ్ ప్లాట్‌ఫారమ్ ద్వారా రూపొందించబడింది"
  },
  hi: {
    reportTitle: "एग्रीशील्ड AI — फसल स्वास्थ्य रिपोर्ट",
    farmer: "किसान का नाम",
    location: "स्थान / गाँव",
    date: "दिनांक",
    crop: "फसल",
    diagnosis: "रोग निदान",
    confidence: "AI सटीकता",
    severity: "गंभीरता स्तर",
    medicines: "अनुशंसित दवाएं और खुराक",
    organic: "जैविक और प्राकृतिक उपचार",
    fieldReq: "खेत छिड़काव आवश्यकता",
    waterVolume: "आवश्यक पानी की मात्रा",
    sprayTanks: "स्प्रे टैंक",
    knapsackNote: "नेप्सैक पंप (15 लीटर प्रति पंप)",
    prevention: "रोकथाम और सावधानियां",
    rxId: "प्रिस्क्रिप्शन आईडी",
    clinicVerified: "क्लिनिक सत्यापित",
    prescribedChemical: "अनुशंसित कृषि रसायन",
    dosage: "अनुशंसित मात्रा",
    spraySchedule: "छिड़काव अंतराल",
    phi: "कटाई से पहले का समय (PHI)",
    sprayConditions: "सुबह 9:00 बजे से पहले या शाम 4:00 बजे के बाद छिड़काव करें। 4 घंटे के भीतर बारिश की संभावना होने पर छिड़काव न करें।",
    bioHeader: "जैविक एवं प्राकृतिक विकल्प",
    culturalPractice: "कृषि पद्धति",
    fieldArea: "खेत का क्षेत्रफल",
    footerTitle: "एग्रीशील्ड प्रिसिजन AI विज़न इंजन",
    footerSub: "पायटॉर्च एवं एनवीडिया निम माइक्रोसर्विसेज द्वारा संचालित",
    footerGov: "सरकारी मंडी एवं कृषि मानकों के अनुरूप",
    stampLab: "एग्रीशील्ड क्लिनिकल लैब",
    stampType: "डिजिटल फसल टेली-डायग्नोस्टिक",
    footerCredit: "एग्रीशील्ड AI स्मार्ट कृषि प्लेटफॉर्म द्वारा निर्मित"
  },
  ta: {
    reportTitle: "அக்ரிஷீல்ட் AI — பயிர் நல அறிக்கை",
    farmer: "விவசாயி பெயர்",
    location: "இடம் / கிராமம்",
    date: "தேதி",
    crop: "பயிர்",
    diagnosis: "நோய் கண்டறிதல்",
    confidence: "AI துல்லியம்",
    severity: "தீவிர நிலை",
    medicines: "பரிந்துரைக்கப்பட்ட மருந்துகள் & அளவு",
    organic: "இயற்கை மற்றும் உயிரியல் முறைகள்",
    fieldReq: "வயல் தெளிப்பு தேவை",
    waterVolume: "தேவையான தண்ணீர் அளவு",
    sprayTanks: "தெளிப்பான் டாங்கிகள்",
    knapsackNote: "நேப்சாக் பம்புகள் (15 லிட்டர் அளவு)",
    prevention: "தடுப்பு முறைகள்",
    rxId: "மருந்து சீட்டு எண்",
    clinicVerified: "மருத்துவமனை சரிபார்க்கப்பட்டது",
    prescribedChemical: "பரிந்துரைக்கப்பட்ட பூச்சிக்கொல்லி",
    dosage: "பரிந்துரைக்கப்பட்ட அளவு",
    spraySchedule: "தெளிக்கும் இடைவெளி",
    phi: "அறுவடைக்கு முந்தைய காலம் (PHI)",
    sprayConditions: "காலை 9:00 மணிக்கு முன் அல்லது மாலை 4:00 மணிக்கு பின் தெளிக்கவும். 4 மணி நேரத்திற்குள் மழை பெய்ய வாய்ப்பிருந்தால் தெளிக்க வேண்டாம்.",
    bioHeader: "இயற்கை மற்றும் உயிரியல் மாற்றுகள்",
    culturalPractice: "விவசாய முறை",
    fieldArea: "நிலப்பரப்பு",
    footerTitle: "அக்ரிஷீல்ட் துல்லிய AI பார்வை இயந்திரம்",
    footerSub: "பைடார்ச் மற்றும் என்விடியா தொழில்நுட்பம்",
    footerGov: "அரசு விவசாய தரநிலைகளுக்கு இணங்க",
    stampLab: "அக்ரிஷீல்ட் மருத்துவ ஆய்வகம்",
    stampType: "டிஜிட்டல் பயிர் மருத்துவம்",
    footerCredit: "அக்ரிஷீல்ட் AI ஸ்மார்ட் விவசாய தளம்"
  },
  kn: {
    reportTitle: "ಅಗ್ರಿಶೀಲ್ಡ್ AI — ಬೆಳೆ ಆರೋಗ್ಯ ವರದಿ",
    farmer: "ರೈತರ ಹೆಸರು",
    location: "ಸ್ಥಳ / ಗ್ರಾಮ",
    date: "ದಿನಾಂಕ",
    crop: "ಬೆಳೆ",
    diagnosis: "ರೋಗ ಪತ್ತೆ",
    confidence: "AI ನಿಖರತೆ",
    severity: "ತೀವ್ರತೆಯ ಮಟ್ಟ",
    medicines: "ಶಿಫಾರಸು ಮಾಡಿದ ಔಷಧಿಗಳು ಮತ್ತು ಪ್ರಮಾಣ",
    organic: "ಸಾವಯವ ಮತ್ತು ಜೈವಿಕ ನಿಯಂತ್ರಣ",
    fieldReq: "ಸಿಂಪರಣೆ ಅಗತ್ಯತೆ",
    waterVolume: "ಅಗತ್ಯವಿರುವ ನೀರಿನ ಪ್ರಮಾಣ",
    sprayTanks: "ಸಿಂಪರಣಾ ಟ್ಯಾಂಕ್‌ಗಳು",
    knapsackNote: "ನ್ಯಾಪ್‌ಸ್ಯಾಕ್ ಪಂಪ್‌ಗಳು (15 ಲೀಟರ್ ಸಾಮರ್ಥ್ಯ)",
    prevention: "ಮುನ್ನೆಚ್ಚರಿಕೆ ಕ್ರಮಗಳು",
    rxId: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಐಡಿ",
    clinicVerified: "ಕ್ಲಿನಿಕ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    prescribedChemical: "ಶಿಫಾರಸು ಮಾಡಿದ ಕೃಷಿ ರಾಸಾಯನಿಕ",
    dosage: "ಶಿಫಾರಸು ಪ್ರಮಾಣ",
    spraySchedule: "ಸಿಂಪರಣೆ ವೇಳಾಪಟ್ಟಿ",
    phi: "ಕೊಯ್ಲಿಗೆ ಮುಂಚಿನ ದಿನಗಳು (PHI)",
    sprayConditions: "ಬೆಳಿಗ್ಗೆ 9:00 ಗಂಟೆಯ ಮೊದಲು ಅಥವಾ ಸಂಜೆ 4:00 ಗಂಟೆಯ ನಂತರ ಸಿಂಪಡಿಸಿ. 4 ಗಂಟೆಗಳಲ್ಲಿ ಮಳೆ ಬರುವ ಸಾಧ್ಯತೆ ಇದ್ದರೆ ಸಿಂಪಡಿಸಬೇಡಿ.",
    bioHeader: "ಸಾವಯವ ಮತ್ತು ಜೈವಿಕ ಪರ್ಯಾಯಗಳು",
    culturalPractice: "ಕೃಷಿ ಪದ್ಧತಿ",
    fieldArea: "ಜಮೀನಿನ ವಿಸ್ತೀರ್ಣ",
    footerTitle: "ಅಗ್ರಿಶೀಲ್ಡ್ ನಿಖರ AI ತಂತ್ರಜ್ಞಾನ",
    footerSub: "ಪೈಟಾರ್ಚ್ ಮತ್ತು ಎನ್‌ವಿಡಿಯಾ ತಂತ್ರಜ್ಞಾನ",
    footerGov: "ಸರ್ಕಾರಿ ಮಾರುಕಟ್ಟೆ ಗುಣಮಟ್ಟಕ್ಕೆ ಅನುಗುಣವಾಗಿದೆ",
    stampLab: "ಅಗ್ರಿಶೀಲ್ಡ್ ಕ್ಲಿನಿಕಲ್ ಲ್ಯಾಬ್",
    stampType: "ಡಿಜಿಟಲ್ ಬೆಳೆ ಆಸ್ಪತ್ರೆ",
    footerCredit: "ಅಗ್ರಿಶೀಲ್ಡ್ AI ಕೃಷಿ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್"
  }
};

const getDictionary = (lang = 'en') => {
  const code = (lang || 'en').toLowerCase().slice(0, 2);
  return RX_TRANSLATIONS[code] || RX_TRANSLATIONS.en;
};

/**
 * Generates formatted WhatsApp diagnostic text in farmer's native language and opens WhatsApp share URL
 */
export const shareDiagnosticToWhatsApp = ({
  cropName = 'Crop',
  diseaseName = 'Foliar Infection',
  confidence = 98,
  severity = 'Moderate',
  chemicals = [],
  organic = [],
  prevention = '',
  acres = 1.0,
  farmLocation = 'Field Sector',
  farmerName = 'Farmer',
  language = 'en'
}) => {
  const d = getDictionary(language);
  const dateStr = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const waterLiters = Math.round(acres * 150);
  const tankPumps = Math.ceil(waterLiters / 15);

  const cleanChemicals = Array.isArray(chemicals) && chemicals.length > 0 
    ? chemicals.map(c => `  💊 ${c}`).join('\n')
    : '  💊 Consult local agronomy officer for registered chemical spray.';

  const cleanOrganic = Array.isArray(organic) && organic.length > 0
    ? organic.map(o => `  🌿 ${o}`).join('\n')
    : '  🌿 Neem oil (5ml/L) or Trichoderma viride foliar wash.';

  const message = 
`🌾 *${d.reportTitle}* 🌾
━━━━━━━━━━━━━━━━━━━━
👨‍🌾 *${d.farmer}:* ${farmerName}
📍 *${d.location}:* ${farmLocation}
📅 *${d.date}:* ${dateStr}

🌱 *${d.crop}:* ${cropName}
🚨 *${d.diagnosis}:* ${diseaseName}
🎯 *${d.confidence}:* ${confidence}%
⚠️ *${d.severity}:* ${severity}

💊 *${d.medicines}:*
${cleanChemicals}

🌿 *${d.organic}:*
${cleanOrganic}

🚜 *${d.fieldReq} (${acres} Acres):*
  • ${d.waterVolume}: ~${waterLiters} L
  • ${d.sprayTanks}: ~${tankPumps} ${d.knapsackNote}

🛡️ *${d.prevention}:*
${prevention || 'Maintain clean irrigation, weed borders, and crop rotation.'}

━━━━━━━━━━━━━━━━━━━━
${d.footerCredit}
Verified with NVIDIA NIM & PyTorch Vision Engine`;

  const url = `https://api.whatsapp.com/send?text=${encodeURIComponent(message)}`;
  window.open(url, '_blank');
};

/**
 * Generates and triggers a 1-page printable clinical Prescription Slip in the farmer's language
 */
export const printPrescriptionSlip = ({
  cropName = 'Crop',
  diseaseName = 'Foliar Infection',
  confidence = 98,
  severity = 'Moderate',
  chemicals = [],
  organic = [],
  prevention = '',
  acres = 1.0,
  farmLocation = 'Pasupugallu',
  farmerName = 'Farmer',
  doctorNote = 'Early foliar spray recommended before dewfall.',
  language = 'en'
}) => {
  const d = getDictionary(language);
  const dateStr = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const waterLiters = Math.round(acres * 150);
  const tankPumps = Math.ceil(waterLiters / 15);
  const rxId = 'AGRI-RX-' + Math.floor(100000 + Math.random() * 900000);

  const printWindow = window.open('', '_blank', 'width=850,height=1100');
  if (!printWindow) {
    alert('Please allow pop-ups in your browser to download or print the Prescription Slip.');
    return;
  }

  const htmlContent = `
<!DOCTYPE html>
<html lang="${language || 'en'}">
<head>
  <meta charset="UTF-8">
  <title>AgriShield AI Prescription - ${rxId}</title>
  <style>
    @page { size: A4 portrait; margin: 15mm; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #1a202c;
      margin: 0;
      padding: 24px;
      line-height: 1.4;
      background: #fff;
    }
    .header {
      border-bottom: 3px solid #059669;
      padding-bottom: 12px;
      margin-bottom: 16px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .brand {
      font-size: 24px;
      font-weight: 900;
      color: #065f46;
      letter-spacing: -0.5px;
    }
    .brand span { color: #10b981; }
    .sub-brand {
      font-size: 11px;
      font-weight: bold;
      color: #6b7280;
      text-transform: uppercase;
      letter-spacing: 1px;
    }
    .meta-box {
      text-align: right;
      font-size: 11px;
      color: #4b5563;
    }
    .meta-box strong { color: #111827; }
    
    .patient-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 10px;
      background: #f0fdf4;
      border: 1px solid #bbf7d0;
      border-radius: 12px;
      padding: 12px 16px;
      margin-bottom: 18px;
    }
    .grid-cell { font-size: 12px; }
    .grid-label { font-size: 10px; font-weight: bold; color: #047857; text-transform: uppercase; }
    .grid-val { font-weight: 800; color: #0f172a; margin-top: 2px; }

    .rx-title {
      font-size: 18px;
      font-weight: 900;
      color: #065f46;
      display: flex;
      align-items: center;
      gap: 8px;
      margin-bottom: 10px;
      border-bottom: 1px solid #e5e7eb;
      padding-bottom: 6px;
    }
    .rx-badge {
      font-size: 11px;
      background: #fee2e2;
      color: #b91c1c;
      padding: 2px 8px;
      border-radius: 999px;
      font-weight: bold;
    }
    
    table.med-table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 16px;
      font-size: 12px;
    }
    table.med-table th {
      background: #047857;
      color: white;
      text-align: left;
      padding: 8px 10px;
      font-size: 11px;
      text-transform: uppercase;
    }
    table.med-table td {
      border-bottom: 1px solid #e5e7eb;
      padding: 8px 10px;
      color: #374151;
    }
    table.med-table tr:nth-child(even) { background: #f9fafb; }

    .spray-box {
      background: #eff6ff;
      border: 1px dashed #60a5fa;
      border-radius: 10px;
      padding: 12px 14px;
      margin-bottom: 16px;
      font-size: 11px;
    }
    .spray-box h4 {
      margin: 0 0 6px 0;
      color: #1d4ed8;
      font-size: 12px;
      font-weight: bold;
    }

    .organic-box {
      background: #fafaf9;
      border: 1px solid #e7e5e4;
      border-radius: 10px;
      padding: 10px 14px;
      margin-bottom: 16px;
      font-size: 11px;
    }
    .organic-box h4 {
      margin: 0 0 4px 0;
      color: #44403c;
      font-size: 11px;
      text-transform: uppercase;
    }

    .footer {
      border-top: 2px solid #e5e7eb;
      padding-top: 14px;
      margin-top: 24px;
      display: flex;
      justify-content: space-between;
      align-items: flex-end;
      font-size: 10px;
      color: #6b7280;
    }
    .stamp-box {
      text-align: center;
      border: 2px dashed #059669;
      border-radius: 8px;
      padding: 6px 14px;
      color: #059669;
      font-weight: 800;
      font-size: 10px;
      line-height: 1.3;
    }
  </style>
</head>
<body>

  <div class="header">
    <div>
      <div class="brand">AgriShield <span>AI</span></div>
      <div class="sub-brand">Autonomous Crop Clinic & Smart Pathology Sentinel</div>
    </div>
    <div class="meta-box">
      <div><strong>${d.rxId}:</strong> ${rxId}</div>
      <div><strong>${d.date}:</strong> ${dateStr}</div>
      <div><strong>Status:</strong> ${d.clinicVerified}</div>
    </div>
  </div>

  <div class="patient-grid">
    <div class="grid-cell">
      <div class="grid-label">${d.farmer}</div>
      <div class="grid-val">${farmerName}</div>
    </div>
    <div class="grid-cell">
      <div class="grid-label">${d.location}</div>
      <div class="grid-val">${farmLocation}</div>
    </div>
    <div class="grid-cell">
      <div class="grid-label">${d.crop}</div>
      <div class="grid-val">${cropName}</div>
    </div>
    <div class="grid-cell">
      <div class="grid-label">${d.fieldArea}</div>
      <div class="grid-val">${acres} Acres</div>
    </div>
  </div>

  <div class="rx-title">
    <span>℞ ${d.diagnosis}: ${diseaseName}</span>
    <span class="rx-badge">${d.confidence}: ${confidence}%</span>
  </div>

  <table class="med-table">
    <thead>
      <tr>
        <th style="width: 35%;">${d.prescribedChemical}</th>
        <th style="width: 25%;">${d.dosage}</th>
        <th style="width: 25%;">${d.spraySchedule}</th>
        <th style="width: 15%;">${d.phi}</th>
      </tr>
    </thead>
    <tbody>
      ${chemicals.map(c => `
        <tr>
          <td><strong>${c.split('@')[0] || c}</strong></td>
          <td>${c.split('@')[1] ? c.split('@')[1].split('(')[0] : 'As per label'}</td>
          <td>Every 7–10 days</td>
          <td>14 Days</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="spray-box">
    <h4>🚜 ${d.fieldReq} (${acres} Acres):</h4>
    <div>• <strong>${d.waterVolume}:</strong> ~${waterLiters} Liters (${acres} acres × 150 L/acre)</div>
    <div>• <strong>${d.sprayTanks}:</strong> ~${tankPumps} ${d.knapsackNote}</div>
    <div>• <strong>Optimal Spray Conditions:</strong> ${d.sprayConditions}</div>
  </div>

  <div class="organic-box">
    <h4>🌱 ${d.bioHeader}:</h4>
    <div>${organic.join(' • ') || 'Neem oil spray (5ml/L) + Trichoderma viride biological wash.'}</div>
    <div style="margin-top: 4px;">• <strong>${d.culturalPractice}:</strong> ${prevention || 'Practice clean crop rotation and discard infected foliage.'}</div>
  </div>

  <div class="footer">
    <div>
      <div><strong>${d.footerTitle}</strong></div>
      <div>${d.footerSub}</div>
      <div>${d.footerGov}</div>
    </div>
    <div class="stamp-box">
      <div>✓ ${d.stampLab}</div>
      <div>${d.stampType}</div>
    </div>
  </div>

  <script>
    window.onload = function() {
      window.print();
    };
  </script>
</body>
</html>
  `;

  printWindow.document.open();
  printWindow.document.write(htmlContent);
  printWindow.document.close();
};
